version: 2
updates:
  - package-ecosystem: cargo
    directory: /webui
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore(deps)"
    groups:
      cargo-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    commit-message:
      prefix: "ci(deps)"
    groups:
      github-actions:
        patterns:
          - "*"
