//! Wire protocol mirror for herdr 0.9.0 (client protocol 22).
//!
//! This module mirrors the subset of herdr's `src/protocol/wire.rs` that the
//! WebUI client and the embedded built-in backend speak over the local client
//! socket. Framing is `[u32LE length][bincode payload]` using
//! `bincode::config::standard()`, exactly like herdr.
//!
//! herdr 0.9.0 requires an exact protocol version match: the handshake sends
//! `TerminalHello{version: PROTOCOL_VERSION}` and any other version is
//! rejected with a `Welcome{error}` before the connection closes. The old
//! multi-version fallback loop never functioned because herdr closes
//! mismatched handshakes instead of staying open for a retry.

use std::io::{Read, Write};

use serde::{Deserialize, Serialize};

/// Client protocol version spoken by herdr 0.9.0.
///
/// herdr validates this exact value at handshake time; there is no
/// cross-version compatibility window.
// Kept even though the server owns its own copy: this documents the client
// protocol this module mirrors and is referenced by protocol tests.
#[allow(dead_code)]
pub(crate) const PROTOCOL_VERSION: u32 = 22;
/// Minimum herdr backend version this WebUI supports.
#[allow(dead_code)]
pub(crate) const MIN_BACKEND_VERSION: &str = "0.9.0";
/// Maximum herdr backend version this WebUI has been tested against.
#[allow(dead_code)]
pub(crate) const MAX_TESTED_BACKEND_VERSION: &str = "0.9.0";

pub(crate) fn write_message<W: Write, M: Serialize>(writer: &mut W, msg: &M) -> Result<(), String> {
    let payload = bincode::serde::encode_to_vec(msg, bincode::config::standard())
        .map_err(|err| err.to_string())?;
    let len = u32::try_from(payload.len()).map_err(|_| "payload too large".to_string())?;
    writer
        .write_all(&len.to_le_bytes())
        .map_err(|err| err.to_string())?;
    writer.write_all(&payload).map_err(|err| err.to_string())?;
    writer.flush().map_err(|err| err.to_string())?;
    Ok(())
}

pub(crate) fn read_message<R: Read, M: for<'de> Deserialize<'de>>(
    reader: &mut R,
    max_frame_size: usize,
) -> Result<M, String> {
    let mut len_buf = [0u8; 4];
    reader
        .read_exact(&mut len_buf)
        .map_err(|err| err.to_string())?;
    let len = u32::from_le_bytes(len_buf) as usize;
    if len > max_frame_size {
        return Err(format!("frame size {len} exceeds maximum {max_frame_size}"));
    }
    let mut payload = vec![0u8; len];
    reader
        .read_exact(&mut payload)
        .map_err(|err| err.to_string())?;
    let (msg, consumed) = bincode::serde::decode_from_slice(&payload, bincode::config::standard())
        .map_err(|err| err.to_string())?;
    if consumed != len {
        return Err("trailing bytes in frame".into());
    }
    Ok(msg)
}

// ---------------------------------------------------------------------------
// Client → Server messages
// ---------------------------------------------------------------------------

/// Render payload encoding negotiated during client handshake.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum RenderEncoding {
    SemanticFrame,
    TerminalAnsi,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientKeyKind {
    Press,
    Repeat,
    Release,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientKeyCode {
    Backspace,
    Enter,
    Left,
    Right,
    Up,
    Down,
    Home,
    End,
    PageUp,
    PageDown,
    Tab,
    BackTab,
    Delete,
    Insert,
    Esc,
    Char(char),
    F(u8),
    Null,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientMouseButton {
    Left,
    Right,
    Middle,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientMouseKind {
    Down(ClientMouseButton),
    Up(ClientMouseButton),
    Drag(ClientMouseButton),
    Moved,
    ScrollUp,
    ScrollDown,
    ScrollLeft,
    ScrollRight,
}

// Wire mirrors: the browser sends plain bytes, but herdr sends these event
// shapes, so the types stay for wire documentation and deserialization.
#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientInputEvent {
    Key {
        code: ClientKeyCode,
        modifiers: u8,
        kind: ClientKeyKind,
        /// Key repeat count from the host terminal.
        repeat_count: u16,
        /// Text generated by this key event, if any.
        generated_text: Option<String>,
        /// Input source metadata.
        source: ClientKeySource,
    },
    TextCommit(String),
    Mouse {
        kind: ClientMouseKind,
        column: u16,
        row: u16,
        modifiers: u8,
    },
    Paste {
        text: String,
    },
    FocusGained,
    FocusLost,
}

/// Source of a key event. A web client always synthesizes keys, so the other
/// variants only need to deserialize.
#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientKeySource {
    Synthesized,
    Vt { bytes: Vec<u8> },
    WindowsConsole { record: WindowsKeyRecord },
}

/// Wire-compatible mirror of herdr's `input::WindowsKeyRecord` for
/// deserializing `ClientKeySource::WindowsConsole`. A web client never
/// produces this but must accept it from Windows backends.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct WindowsKeyRecord {
    pub(crate) key_down: bool,
    pub(crate) repeat_count: u16,
    pub(crate) virtual_key_code: u16,
    pub(crate) virtual_scan_code: u16,
    pub(crate) unicode: u16,
    pub(crate) control_key_state: u32,
}

/// Size of a pane surface requested by a client-owned shell.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ClientSurfaceSize {
    pub(crate) cols: u16,
    pub(crate) rows: u16,
}

/// Terminal target of a clipboard image read by the client.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientClipboardImageTarget {
    DirectTerminal,
    Pane(String),
    Popup(String),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientHostDefaultColorKind {
    Foreground,
    Background,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientHostAppearance {
    Dark,
    Light,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientHostThemeUpdate {
    DefaultColor {
        kind: ClientHostDefaultColorKind,
        color: ClientHostColor,
    },
    PaletteColors(Vec<(u8, ClientHostColor)>),
    Appearance(ClientHostAppearance),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ClientHostColor {
    pub(crate) r: u8,
    pub(crate) g: u8,
    pub(crate) b: u8,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum AttachScrollDirection {
    Up,
    Down,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum AttachScrollSource {
    Wheel,
    PageKey {
        /// Original key bytes to forward when the child application owns page keys.
        input: Vec<u8>,
    },
}

/// Messages sent from the client to the server over the client protocol
/// socket. Variant order mirrors herdr 0.9.0's `ClientMessage` exactly;
/// bincode encodes the variant index, so any drift breaks the handshake.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientMessage {
    /// Direct terminal handshake. herdr 0.9.0 renamed `Hello` to
    /// `TerminalHello` and dropped `requested_encoding`, `keybindings`, and
    /// `launch_mode`: direct terminal clients always get `TerminalAnsi`
    /// encoding and attach mode is implied by `AttachTerminal`.
    TerminalHello {
        /// Protocol version the client speaks. Must equal 22.
        version: u32,
        /// Terminal width in columns.
        cols: u16,
        /// Terminal height in rows.
        rows: u16,
        /// Width of a terminal cell in physical pixels, or 0 when
        /// client-side Kitty graphics are disabled.
        cell_width_px: u32,
        /// Height of a terminal cell in physical pixels, or 0 when
        /// unavailable.
        cell_height_px: u32,
        /// Whether the client can report exact SGR pixel mouse geometry.
        pixel_mouse: bool,
    },

    /// Raw input bytes read from the client's stdin.
    Input { data: Vec<u8> },

    /// Image bytes read from the client's local clipboard for remote paste bridging.
    ClipboardImage {
        target: ClientClipboardImageTarget,
        extension: String,
        data: Vec<u8>,
    },

    /// Terminal resize notification from the client.
    Resize {
        cols: u16,
        rows: u16,
        cell_width_px: u32,
        cell_height_px: u32,
        /// Whether this resize carries coherent exact geometry for SGR pixel
        /// mouse input.
        pixel_mouse: bool,
    },

    /// Graceful disconnect request.
    Detach,

    /// Switch this connection into direct terminal attach mode.
    AttachTerminal { terminal_id: String, takeover: bool },

    /// Scroll input handled by a direct terminal attach client.
    AttachScroll {
        source: AttachScrollSource,
        direction: AttachScrollDirection,
        lines: u16,
        column: Option<u16>,
        row: Option<u16>,
        modifiers: u8,
    },

    /// Switch this connection into read-only terminal observe mode.
    ObserveTerminal { target: String },

    /// Switch this connection into writable terminal control mode.
    ControlTerminal { target: String, takeover: bool },

    /// Result of the one armed Herdr-owned direct Kitty transmission.
    GraphicsTransmissionResult {
        transfer_id: u64,
        image_id: u32,
        success: bool,
    },

    /// The direct command was written and flushed; terminal response timing starts now.
    GraphicsTransmissionStarted { transfer_id: u64, image_id: u32 },

    /// Handshake for the client-owned shell around one pane surface. The
    /// WebUI is a direct terminal client, not a client-owned shell, so this
    /// variant only needs to deserialize.
    ClientShellHello {
        version: u32,
        cell_width_px: u32,
        cell_height_px: u32,
        surface_size: ClientSurfaceSize,
        pixel_mouse: bool,
        direct_graphics: bool,
        endpoint_keybindings: bool,
        mouse_capture: bool,
    },

    /// Resize the pane viewport of a client-owned shell.
    ClientShellResize {
        cell_width_px: u32,
        cell_height_px: u32,
        surface_size: ClientSurfaceSize,
        pixel_mouse: bool,
    },

    /// Deliver client-classified semantic input directly to a stable pane target.
    ClientShellPaneInput {
        pane_id: String,
        events: Vec<ClientPaneInputEvent>,
    },

    /// Deliver client-classified semantic input to the active popup terminal.
    ClientShellPopupInput {
        terminal_id: String,
        events: Vec<ClientPaneInputEvent>,
    },

    /// Invoke one endpoint operation through this client shell's selected connection.
    ClientShellEndpointRequest { boot_id: String, request: String },

    /// Deliver one structured mouse event to a directly attached terminal.
    AttachMouse {
        kind: ClientMouseKind,
        position: ClientMousePosition,
        geometry: Option<ClientMouseGeometry>,
        modifiers: u8,
        lines: u16,
    },

    /// Publish one host terminal color or appearance update observed by a client-owned shell.
    ClientShellHostTheme { update: ClientHostThemeUpdate },

    /// Publish whether the outer terminal containing a client shell has focus.
    ClientShellFocus { focused: bool },

    /// Update this client's shell mouse-capture preference after config reload.
    ClientShellMouseCapture { enabled: bool },

    /// Extensible named control message for the stable client-owned endpoint
    /// protocol. Append-only; the two-string payload is fixed.
    EndpointControl { kind: String, data: String },
}

/// Pane-domain input after the client has classified and consumed shell actions.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientPaneInputEvent {
    Key {
        code: ClientKeyCode,
        modifiers: u8,
        kind: ClientKeyKind,
        repeat_count: u16,
        shifted_codepoint: Option<u32>,
        generated_text: Option<String>,
        tracks_release: bool,
        physical_key_id: Option<u32>,
        windows_record: Option<WindowsKeyRecord>,
    },
    TextCommit(String),
    Mouse {
        kind: ClientMouseKind,
        position: ClientMousePosition,
        geometry: Option<ClientMouseGeometry>,
        modifiers: u8,
        lines: u16,
    },
    Paste(String),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientMousePosition {
    Cell {
        column: u16,
        row: u16,
    },
    Pixels {
        x: u32,
        y: u32,
        column: u16,
        row: u16,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ClientMouseGeometry {
    pub(crate) cols: u16,
    pub(crate) rows: u16,
    pub(crate) width_px: u32,
    pub(crate) height_px: u32,
}

// ---------------------------------------------------------------------------
// Server → Client messages
// ---------------------------------------------------------------------------

/// A single cell in a rendered frame, serialized independently from ratatui's
/// `Cell` type to keep the wire protocol stable.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct CellData {
    pub(crate) symbol: String,
    pub(crate) fg: u32,
    pub(crate) bg: u32,
    pub(crate) modifier: u16,
    pub(crate) skip: bool,
    pub(crate) hyperlink: Option<u32>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct CursorState {
    pub(crate) x: u16,
    pub(crate) y: u16,
    pub(crate) visible: bool,
    #[serde(default)]
    pub(crate) shape: u8,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct FrameData {
    pub(crate) cells: Vec<CellData>,
    pub(crate) width: u16,
    pub(crate) height: u16,
    pub(crate) cursor: Option<CursorState>,
    pub(crate) hyperlinks: Vec<String>,
    pub(crate) graphics: Vec<u8>,
}

/// Terminal ANSI bytes encoded by the server for network-efficient clients.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct TerminalFrame {
    pub(crate) seq: u64,
    pub(crate) width: u16,
    pub(crate) height: u16,
    pub(crate) full: bool,
    pub(crate) bytes: Vec<u8>,
}

/// Notification kind forwarded from server to client.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum NotifyKind {
    Sound,
    Toast,
    SystemToast,
}

/// A client-rendered notification category.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum SemanticNotificationKind {
    NeedsAttention,
    Finished,
    UpdateInstalled,
    Custom,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum SemanticNotificationSound {
    Done,
    Request,
}

/// Toast placement requested for herdr-originated toasts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub(crate) enum ToastHerdrPosition {
    TopLeft,
    TopRight,
    BottomLeft,
    BottomRight,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct SemanticNotification {
    pub(crate) kind: SemanticNotificationKind,
    pub(crate) title: String,
    pub(crate) body: Option<String>,
    pub(crate) sound: Option<SemanticNotificationSound>,
    pub(crate) agent: Option<String>,
    pub(crate) workspace_id: Option<String>,
    pub(crate) tab_id: Option<String>,
    pub(crate) pane_id: Option<String>,
    pub(crate) position: Option<ToastHerdrPosition>,
}

/// Agent status reported by the endpoint projection.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum AgentStatus {
    Idle,
    Working,
    Blocked,
    Done,
    Unknown,
}

impl AgentStatus {
    #[allow(dead_code)]
    pub(crate) fn from_str(value: &str) -> Self {
        match value {
            "idle" => Self::Idle,
            "working" => Self::Working,
            "blocked" => Self::Blocked,
            "done" => Self::Done,
            _ => Self::Unknown,
        }
    }
}

/// Initial resource projection used by the stable client-owned shell.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ClientShellSnapshot {
    pub(crate) boot_id: String,
    pub(crate) revision: u64,
    pub(crate) config_diagnostic: Option<String>,
    pub(crate) product_announcement: Option<ClientShellProductAnnouncement>,
    pub(crate) update_available: Option<String>,
    pub(crate) update_install_command: String,
    pub(crate) server_keybindings_toml: Option<String>,
    pub(crate) latest_release_notes_available: bool,
    pub(crate) integration_updates_available: bool,
    pub(crate) worktree_directory: String,
    pub(crate) release_notes: Option<ClientShellReleaseNotes>,
    pub(crate) focused_workspace_id: Option<String>,
    pub(crate) focused_tab_id: Option<String>,
    pub(crate) focused_pane_id: Option<String>,
    pub(crate) tab_bar_right: Vec<ClientShellTabStatusSegment>,
    pub(crate) tab_bar_right_separator: String,
    pub(crate) agent_view_label: Option<String>,
    pub(crate) agent_order: Vec<String>,
    pub(crate) workspaces: Vec<ClientShellWorkspace>,
    pub(crate) tabs: Vec<ClientShellTab>,
    pub(crate) panes: Vec<ClientShellPane>,
    pub(crate) agents: Vec<ClientShellAgent>,
    pub(crate) commands: Vec<ClientShellCommand>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ClientShellProductAnnouncement {
    pub(crate) version: String,
    pub(crate) id: String,
    pub(crate) title: String,
    pub(crate) body: String,
    pub(crate) preview: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ClientShellReleaseNotes {
    pub(crate) version: String,
    pub(crate) body: String,
    pub(crate) preview: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientShellCommandAction {
    Shell,
    Pane,
    Popup,
    PluginAction,
    /// A future endpoint action kind that this client cannot execute.
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ClientShellCommand {
    pub(crate) command_id: String,
    pub(crate) binding_label: String,
    pub(crate) binding_labels: Vec<String>,
    pub(crate) action: ClientShellCommandAction,
    pub(crate) description: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ClientShellTabStatusSegment {
    pub(crate) text: String,
    pub(crate) accent: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ClientShellWorkspace {
    pub(crate) workspace_id: String,
    pub(crate) active_tab_id: String,
    pub(crate) new_workspace_cwd: String,
    pub(crate) number: usize,
    pub(crate) label: String,
    pub(crate) custom_label: bool,
    pub(crate) branch: Option<String>,
    pub(crate) git_ahead_behind: Option<(usize, usize)>,
    pub(crate) tokens: Vec<(String, String)>,
    pub(crate) worktree: Option<ClientShellWorktree>,
    pub(crate) focused: bool,
    pub(crate) agent_status: AgentStatus,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ClientShellWorktree {
    pub(crate) key: String,
    pub(crate) label: String,
    pub(crate) is_linked_worktree: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ClientShellTab {
    pub(crate) tab_id: String,
    pub(crate) workspace_id: String,
    pub(crate) number: usize,
    pub(crate) label: String,
    pub(crate) custom_label: bool,
    pub(crate) zoomed: bool,
    pub(crate) focused: bool,
    pub(crate) agent_status: AgentStatus,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ClientShellPane {
    pub(crate) pane_id: String,
    pub(crate) workspace_id: String,
    pub(crate) tab_id: String,
    pub(crate) label: Option<String>,
    pub(crate) cwd: Option<String>,
    pub(crate) foreground_cwd: Option<String>,
    pub(crate) focused: bool,
    pub(crate) right_click_passthrough: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ClientShellAgent {
    pub(crate) pane_id: String,
    pub(crate) workspace_id: String,
    pub(crate) tab_id: String,
    pub(crate) name: Option<String>,
    pub(crate) display_agent: Option<String>,
    pub(crate) agent: Option<String>,
    pub(crate) title: Option<String>,
    pub(crate) terminal_title: Option<String>,
    pub(crate) terminal_title_stripped: Option<String>,
    pub(crate) agent_status: AgentStatus,
    pub(crate) state_change_seq: u64,
    pub(crate) state_labels: Vec<(String, String)>,
    pub(crate) tokens: Vec<(String, String)>,
    pub(crate) focused: bool,
}

/// Origin-relative geometry for one pane in a rendered pane surface.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct PaneSurfacePane {
    pub(crate) pane_id: String,
    pub(crate) content_revision: u64,
    pub(crate) rect: SurfaceRect,
    pub(crate) inner_rect: SurfaceRect,
    pub(crate) scrollbar_rect: Option<SurfaceRect>,
    pub(crate) scroll: Option<PaneSurfaceScrollMetrics>,
    pub(crate) focused: bool,
    pub(crate) mouse_reporting: bool,
    pub(crate) sgr_pixel_mouse: bool,
    pub(crate) alternate_screen_active: bool,
    pub(crate) pixel_width: u32,
    pub(crate) pixel_height: u32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct PaneSurfaceScrollMetrics {
    pub(crate) offset_from_bottom: u64,
    pub(crate) max_offset_from_bottom: u64,
    pub(crate) viewport_rows: u64,
}

/// One draggable BSP split handle relative to a pane surface.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct PaneSurfaceSplit {
    pub(crate) direction: PaneSurfaceSplitDirection,
    pub(crate) pos: u16,
    pub(crate) area: SurfaceRect,
    pub(crate) hit_rect: SurfaceRect,
    pub(crate) path: Vec<bool>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum PaneSurfaceSplitDirection {
    Horizontal,
    Vertical,
}

/// Wire-safe rectangle relative to a pane surface.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct SurfaceRect {
    pub(crate) x: u16,
    pub(crate) y: u16,
    pub(crate) width: u16,
    pub(crate) height: u16,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub(crate) enum SurfaceGraphicsTarget {
    Pane { pane_id: String },
    Popup { terminal_id: String },
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub(crate) enum SurfaceGraphicsSource {
    Terminal {
        target: SurfaceGraphicsTarget,
        image_id: u32,
    },
    PaneLayer {
        pane_id: String,
        layer_id: String,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub(crate) enum SurfaceGraphicsFormat {
    Rgb,
    Rgba,
    Png,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub(crate) struct SurfaceGraphicsAssetKey {
    pub(crate) source: SurfaceGraphicsSource,
    pub(crate) image_width: u32,
    pub(crate) image_height: u32,
    pub(crate) format: SurfaceGraphicsFormat,
    pub(crate) data_len: u64,
    pub(crate) data_fingerprint: u64,
}

/// Image bytes newly needed by this connection's complete desired scene.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct SurfaceGraphicsAsset {
    pub(crate) key: SurfaceGraphicsAssetKey,
    pub(crate) data: Vec<u8>,
}

/// One already-clipped desired placement relative to its target surface.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct SurfaceGraphicsPlacement {
    pub(crate) asset: SurfaceGraphicsAssetKey,
    pub(crate) logical_placement_id: u32,
    pub(crate) x: u16,
    pub(crate) y: u16,
    pub(crate) cols: u32,
    pub(crate) rows: u32,
    pub(crate) source_x: u32,
    pub(crate) source_y: u32,
    pub(crate) source_width: u32,
    pub(crate) source_height: u32,
    pub(crate) x_offset: u32,
    pub(crate) y_offset: u32,
    pub(crate) z: i32,
    pub(crate) scrollback_offset: u32,
}

/// Complete desired placements plus only the image bytes not already sent for
/// the current live scene on this connection.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct SurfaceGraphicsScene {
    pub(crate) assets: Vec<SurfaceGraphicsAsset>,
    pub(crate) placements: Vec<SurfaceGraphicsPlacement>,
    pub(crate) retained_assets: Vec<SurfaceGraphicsAssetKey>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientShellPopupSize {
    Cells(u16),
    Percent(u8),
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ClientShellPopupSurface {
    pub(crate) terminal_id: String,
    pub(crate) title: String,
    pub(crate) width: Option<ClientShellPopupSize>,
    pub(crate) height: Option<ClientShellPopupSize>,
    pub(crate) frame: FrameData,
    pub(crate) mouse_reporting: bool,
    pub(crate) sgr_pixel_mouse: bool,
    pub(crate) pixel_width: u32,
    pub(crate) pixel_height: u32,
}

/// One server-rendered active-tab surface without sidebar, tab bar, or overlays.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct PaneSurfaceFrame {
    pub(crate) boot_id: String,
    pub(crate) projection_revision: u64,
    pub(crate) surface_revision: u64,
    pub(crate) frame: FrameData,
    pub(crate) panes: Vec<PaneSurfacePane>,
    pub(crate) splits: Vec<PaneSurfaceSplit>,
    pub(crate) popup: Option<Box<ClientShellPopupSurface>>,
    pub(crate) graphics: SurfaceGraphicsScene,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct PaneSurfacePatchRow {
    pub(crate) x: u16,
    pub(crate) y: u16,
    pub(crate) cells: Vec<CellData>,
}

/// Incremental terminal-cell update against one committed complete pane surface.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct PaneSurfacePatch {
    pub(crate) boot_id: String,
    pub(crate) projection_revision: u64,
    pub(crate) base_surface_revision: u64,
    pub(crate) surface_revision: u64,
    pub(crate) rows: Vec<PaneSurfacePatchRow>,
    pub(crate) panes: Vec<PaneSurfacePane>,
    pub(crate) cursor: Option<CursorState>,
}

/// Messages sent from the server to the client over the client protocol
/// socket. Variant order mirrors herdr 0.9.0's `ServerMessage` exactly; the
/// WebUI acts on `Welcome`, `Terminal`, `Graphics`, `ServerShutdown`,
/// `Notify`, `Clipboard`, `WindowTitle`, and `TerminalBell`, and the rest
/// exist so the proxy can decode and skip them.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ServerMessage {
    /// Handshake response: server acknowledges (or rejects) the client.
    Welcome {
        version: u32,
        encoding: RenderEncoding,
        error: Option<String>,
    },

    /// Terminal bytes to write directly for a terminal-ANSI client.
    Terminal(TerminalFrame),

    /// Client-local Kitty graphics bytes to write directly to the host terminal.
    Graphics { bytes: Vec<u8> },

    /// Server is shutting down. Clients should exit gracefully.
    ServerShutdown { reason: Option<String> },

    /// A notification event (sound/toast) to be rendered locally by the client.
    Notify {
        kind: NotifyKind,
        message: String,
        body: Option<String>,
    },

    /// OSC 52 clipboard data forwarded from a PTY through the server.
    Clipboard { data: String },

    /// Set the foreground client's outer terminal window title.
    WindowTitle { title: Option<String> },

    /// Client-local runtime config changed on disk; refresh it without reconnecting.
    ReloadSoundConfig,

    /// Whether the client should currently capture host mouse input.
    MouseCapture {
        enabled: bool,
        /// True only while the focused pane requests DEC SGR pixel mode 1016.
        sgr_pixels: bool,
    },

    /// Ring the foreground client's outer terminal for pane-originated BEL characters.
    TerminalBell { count: u16 },

    /// One validated Herdr-owned Kitty regular-file RGBA transmission.
    GraphicsFile {
        path: String,
        expected_len: u64,
        image_id: u32,
        transfer_id: u64,
        leading: Vec<u8>,
        control: String,
        /// ClientShell upload identity. `None` targets a direct terminal client.
        surface_asset: Option<SurfaceGraphicsAssetKey>,
    },

    /// Suppress a direct command that expired before terminal delivery.
    GraphicsTransmissionRetired { transfer_id: u64, image_id: u32 },

    /// Initial metadata for a client-owned shell.
    ClientShellSnapshot(Box<ClientShellSnapshot>),

    /// Active-tab pane content rendered at a client-requested origin-relative size.
    PaneSurface(PaneSurfaceFrame),

    /// Ephemeral semantic notification delivered over the private control lane.
    SemanticNotification(SemanticNotification),

    /// Immediate endpoint error that the client-rendered shell must show.
    ClientShellError { message: String },

    /// Exact Kitty keyboard flags requested by a directly attached terminal.
    DirectTerminalKeyboardProtocol {
        flags: u16,
        modify_other_keys_level: u8,
    },

    /// Whether the focused pane or popup needs the shell host to report every key.
    ClientShellKeyboardReportAll { enabled: bool },

    /// One ordered chunk of the final response to an endpoint operation.
    ClientShellEndpointResponseChunk {
        boot_id: String,
        request_id: String,
        final_chunk: bool,
        data: Vec<u8>,
    },

    /// Incremental terminal-cell update for a previously committed pane surface.
    PaneSurfacePatch(PaneSurfacePatch),

    /// Extensible named control message for the stable client-owned endpoint protocol.
    EndpointControl { kind: String, data: String },
}

#[cfg(test)]
mod external_probe_tests {
    //! Live probe against a real, isolated herdr 0.9.0 daemon, proving the
    //! WebUI's `ClientMessage`/`ServerMessage` types can speak the external
    //! backend's ClientShell endpoint protocol and receive pane graphics.
    //!
    //! Gated on `HERDR_WEBUI_EXTERNAL_PROBE` (set to the session data dir
    //! holding `herdr-client.sock`) so normal `cargo test` runs never spawn
    //! or contact daemons. The driver script owns isolation: scratch
    //! `XDG_CONFIG_HOME`, scratch `HERDR_SESSION`, and cleanup.

    use super::*;
    use interprocess::local_socket::Stream as LocalStream;
    use std::io::{Read, Write};
    use std::path::{Path, PathBuf};
    use std::time::{Duration, Instant};

    fn probe_session_dir() -> Option<PathBuf> {
        let dir = std::env::var("HERDR_WEBUI_EXTERNAL_PROBE").ok()?;
        if dir.trim().is_empty() {
            return None;
        }
        Some(PathBuf::from(dir))
    }

    fn client_socket_path() -> PathBuf {
        probe_session_dir()
            .expect("probe enabled")
            .join("herdr-client.sock")
    }

    fn api_socket_path() -> PathBuf {
        probe_session_dir()
            .expect("probe enabled")
            .join("herdr.sock")
    }

    fn connect(path: &Path) -> LocalStream {
        use interprocess::local_socket::{prelude::*, GenericFilePath};
        let name = path.to_fs_name::<GenericFilePath>().unwrap();
        LocalStream::connect(name).unwrap()
    }

    /// Spawns a reader thread for a client-socket stream. The thread pushes
    /// each decoded `ServerMessage` (or an error string) into the channel;
    /// the test side uses `recv_timeout` so deadlines actually fire even
    /// when the server goes quiet. interprocess streams have no read-timeout
    /// API, so this is the only robust way to bound waits.
    fn spawn_reader(mut stream: LocalStream) -> std::sync::mpsc::Receiver<ServerMessage> {
        let (tx, rx) = std::sync::mpsc::channel::<ServerMessage>();
        std::thread::spawn(move || loop {
            let mut len_buf = [0u8; 4];
            if let Err(err) = stream.read_exact(&mut len_buf) {
                let _ = tx.send(panic_marker(format!("client socket read failed: {err}")));
                return;
            }
            let len = u32::from_le_bytes(len_buf) as usize;
            assert!(len <= 32 * 1024 * 1024, "oversized server frame {len}");
            let mut payload = vec![0u8; len];
            if let Err(err) = stream.read_exact(&mut payload) {
                let _ = tx.send(panic_marker(format!("client socket read failed: {err}")));
                return;
            }
            match bincode::serde::decode_from_slice::<ServerMessage, _>(
                &payload,
                bincode::config::standard(),
            ) {
                Ok((message, _)) => {
                    if tx.send(message).is_err() {
                        return;
                    }
                }
                Err(err) => {
                    let _ = tx.send(panic_marker(format!("decode ServerMessage failed: {err}")));
                    return;
                }
            }
        });
        rx
    }

    /// Terminal error frame that makes the poll loop panic with context.
    fn panic_marker(message: String) -> ServerMessage {
        // Reuse ClientShellError: the poll loops treat it as fatal.
        ServerMessage::ClientShellError { message }
    }

    /// Blocking read of one frame; only used where the server is contractually
    /// about to answer immediately (handshake).
    fn read_server_message(rx: &std::sync::mpsc::Receiver<ServerMessage>) -> ServerMessage {
        rx.recv().expect("server frame")
    }
    /// Minimal empty frame, mirroring an unrendered surface.
    fn empty_frame() -> FrameData {
        FrameData {
            cells: Vec::new(),
            width: 0,
            height: 0,
            cursor: None,
            hyperlinks: Vec::new(),
            graphics: Vec::new(),
        }
    }

    /// JSON payload for the `endpoint.hello.v1` EndpointControl handshake.
    /// `direct_graphics` arms the GraphicsFile upload path; the graphics scene
    /// itself is gated on known cell metrics (collect_scene checks
    /// `cell_size.is_known()`), so the probe sends real cell dimensions.
    fn endpoint_hello_json(direct_graphics: bool) -> String {
        serde_json::json!({
            "generation": 1,
            "cell_width_px": 10,
            "cell_height_px": 20,
            "surface_size": { "cols": 80, "rows": 24 },
            "pixel_mouse": true,
            "direct_graphics": direct_graphics,
            "endpoint_keybindings": false,
            "mouse_capture": false,
            "surface_active": true,
            "snapshot_codecs": ["shell.snapshot.v1"],
            "surface_codecs": ["shell.surface.v1"],
            "input_codecs": ["shell.input.semantic.v1"],
            "blob_codecs": ["shell.blob.v1"],
        })
        .to_string()
    }

    fn send_client_message(stream: &mut LocalStream, msg: &ClientMessage) {
        let payload = bincode::serde::encode_to_vec(msg, bincode::config::standard()).unwrap();
        let len = u32::try_from(payload.len()).unwrap();
        stream.write_all(&len.to_le_bytes()).unwrap();
        stream.write_all(&payload).unwrap();
        stream.flush().unwrap();
    }

    /// One newline-delimited JSON API request on a fresh connection. The
    /// server answers once and closes, so `read_to_end` terminates.
    fn api_request(method: &str, params: serde_json::Value) -> serde_json::Value {
        let mut stream = connect(&api_socket_path());
        let req = serde_json::json!({
            "id": format!("probe-{method}"),
            "method": method,
            "params": params,
        });
        stream
            .write_all(serde_json::to_string(&req).unwrap().as_bytes())
            .unwrap();
        stream.write_all(b"\n").unwrap();
        stream.flush().unwrap();
        let mut buf = Vec::new();
        stream.read_to_end(&mut buf).unwrap();
        assert!(
            !buf.is_empty(),
            "empty response for {method}; daemon likely not running"
        );
        serde_json::from_slice(&buf).unwrap()
    }

    fn api_expect_ok(method: &str, params: serde_json::Value) {
        let response = api_request(method, params);
        let result_type = &response["result"]["type"];
        assert_eq!(
            result_type,
            &serde_json::json!("ok"),
            "{method} failed: {response}"
        );
    }

    /// Kitty graphics sequence: direct RGB (f=32) transmit + placement, all
    /// ASCII after the escape bytes. Emitted into a pane, the embedded
    /// Ghostty core parses it into placements and render_and_stream ships
    /// them as a PaneSurface graphics scene.
    fn kitty_rgb_emit_bytes() -> Vec<u8> {
        // Byte-for-byte the sequence herdr's own headless tests feed into a
        // pane to prove scene delivery (tests/pane_graphics.rs): direct
        // RGBA transmit with an explicit image id, then the display action.
        // Ghostty stores f=32 data as RGBA for a 1x1 image, so the asset
        // arrives as [255, 0, 0, 255].
        let mut out = b"\x1b_Ga=T,f=32,t=d,i=7,p=3,s=1,v=1,c=1,r=1,q=2;/wAA/w==\x1b\\".to_vec();
        out.extend_from_slice(b"\x1b_Ga=p,U=1,i=7,c=1,r=1,q=2\x1b\\");
        out
    }

    /// Shell command that re-emits `bytes` onto the PTY. Uses printf's FORMAT
    /// argument (which interprets `\033`) instead of `%s` arguments (which do
    /// not), so the typed command line stays plain ASCII for zsh's line
    /// editor while printf writes the raw Kitty escape bytes.
    fn printf_command(bytes: &[u8]) -> String {
        let mut out = String::from("printf '");
        for &b in bytes {
            match b {
                b'\'' => out.push_str("'\\''"),
                b'\\' => out.push_str("\\\\"),
                0x1b => out.push_str("\\033"),
                0x20..=0x7E => out.push(b as char),
                _ => out.push_str(&format!("\\{:03o}", b)),
            }
        }
        out.push_str("'\n");
        out
    }

    #[test]
    fn external_endpoint_graphics_probe() {
        if probe_session_dir().is_none() {
            return;
        }

        // 1. Endpoint hello as the FIRST client message (client_transport.rs
        //    rejects a bare ClientShellHello in 0.9.0).
        let mut stream = connect(&client_socket_path());
        send_client_message(
            &mut stream,
            &ClientMessage::EndpointControl {
                kind: "endpoint.hello.v1".into(),
                data: endpoint_hello_json(true),
            },
        );
        let rx = spawn_reader(stream);

        // 2. First server frame must be the endpoint welcome.
        let welcome = read_server_message(&rx);
        let ServerMessage::EndpointControl { kind, data } = &welcome else {
            panic!("expected endpoint welcome, got {welcome:?}");
        };
        assert_eq!(kind, "endpoint.welcome.v1");
        let welcome: serde_json::Value = serde_json::from_str(data).unwrap();
        assert_eq!(welcome["generation"], 1);
        assert_eq!(welcome["snapshot_codec"], "shell.snapshot.v1");
        assert_eq!(welcome["surface_codec"], "shell.surface.v1");
        assert_eq!(welcome["input_codec"], "shell.input.semantic.v1");
        assert_eq!(welcome["blob_codec"], "shell.blob.v1");

        // 3. tab.create gives a fresh shell pane and returns its pane id.
        let created = api_request(
            "tab.create",
            serde_json::json!({ "focus": true, "label": "probe" }),
        );
        assert_eq!(
            created["result"]["type"], "tab_created",
            "tab.create failed: {created}"
        );
        let pane_id = created["result"]["root_pane"]["pane_id"]
            .as_str()
            .expect("tab_created missing root_pane.pane_id")
            .to_string();

        // Give the spawned shell a moment to initialize before typing into it.
        std::thread::sleep(Duration::from_millis(1500));

        // 4. Type the Kitty emitter into the pane and press Enter. The pane
        //    is an interactive shell; printf re-emits the bytes onto the PTY
        //    where the Ghostty core captures them as graphics placements.
        let command = printf_command(&kitty_rgb_emit_bytes());
        api_expect_ok(
            "pane.send_text",
            serde_json::json!({ "pane_id": pane_id, "text": command }),
        );

        // 5. PaneSurface frames must arrive, and one must carry graphics.
        let deadline = Instant::now() + Duration::from_secs(15);
        let mut saw_surface = false;
        let mut saw_graphics = false;
        while Instant::now() < deadline {
            let Ok(msg) = rx.recv_timeout(Duration::from_millis(500)) else {
                continue;
            };
            match msg {
                ServerMessage::PaneSurface(frame) => {
                    saw_surface = true;
                    let scene = &frame.graphics;
                    if !scene.assets.is_empty() || !scene.placements.is_empty() {
                        saw_graphics = true;
                        let asset = scene.assets.first().unwrap();
                        println!(
                            "PROBE graphics scene: {} assets, {} placements, {} retained; first asset format={:?} len={} data[0..8]={:02x?}",
                            scene.assets.len(),
                            scene.placements.len(),
                            scene.retained_assets.len(),
                            asset.key.format,
                            asset.data.len(),
                            &asset.data[..asset.data.len().min(8)],
                        );
                        assert_eq!(
                            asset.data,
                            vec![255, 0, 0, 255],
                            "1x1 f=32 asset must decode to red RGBA"
                        );
                        assert_eq!(asset.key.image_width, 1);
                        assert_eq!(asset.key.image_height, 1);
                        assert!(matches!(asset.key.format, SurfaceGraphicsFormat::Rgba));
                        break;
                    }
                }
                ServerMessage::EndpointControl { kind, .. } if kind == "endpoint.snapshot.v1" => {
                    // shell snapshot precedes surfaces; expected.
                }
                ServerMessage::ClientShellError { message } => {
                    panic!("client shell error: {message}");
                }
                _ => {}
            }
        }
        assert!(saw_surface, "never received a PaneSurface frame");
        assert!(
            saw_graphics,
            "no graphics scene arrived with direct_graphics=true"
        );

        // 6. Negative control: a second connection reporting NO cell metrics
        //    (cell 0x0) must receive surfaces without any graphics scene.
        //    In herdr 0.9.0 the scene gate is `cell_size.is_known()`
        //    (kitty_graphics/surface.rs collect_scene); the hello's
        //    `direct_graphics` flag only arms the GraphicsFile upload path.
        let mut plain = connect(&client_socket_path());
        let mut no_cell_hello = endpoint_hello_json(false);
        {
            let mut hello: serde_json::Value = serde_json::from_str(&no_cell_hello).unwrap();
            hello["cell_width_px"] = serde_json::json!(0);
            hello["cell_height_px"] = serde_json::json!(0);
            no_cell_hello = serde_json::to_string(&hello).unwrap();
        }
        send_client_message(
            &mut plain,
            &ClientMessage::EndpointControl {
                kind: "endpoint.hello.v1".into(),
                data: no_cell_hello,
            },
        );
        let rx2 = spawn_reader(plain);
        let welcome2 = read_server_message(&rx2);
        let ServerMessage::EndpointControl { kind, .. } = &welcome2 else {
            panic!("expected endpoint welcome 2, got {welcome2:?}");
        };
        assert_eq!(kind, "endpoint.welcome.v1");

        let deadline = Instant::now() + Duration::from_secs(10);
        let mut frames = 0;
        let mut got_graphics = false;
        while Instant::now() < deadline {
            let Ok(msg) = rx2.recv_timeout(Duration::from_millis(500)) else {
                continue;
            };
            match msg {
                ServerMessage::PaneSurface(frame) => {
                    frames += 1;
                    let scene = &frame.graphics;
                    if !scene.assets.is_empty() || !scene.placements.is_empty() {
                        got_graphics = true;
                        break;
                    }
                }
                ServerMessage::ClientShellError { message } => {
                    panic!("client shell error (negative control): {message}");
                }
                _ => {}
            }
        }
        assert!(frames > 0, "negative control never got a PaneSurface frame");
        assert!(
            !got_graphics,
            "a client with unknown cell size must not receive graphics"
        );
    }

    /// Decode floor: the webui ServerMessage must keep round-tripping herdr
    /// 0.9.0 pane-surface graphics shapes. Plain unit test so parity stays
    /// checked in CI even without the live daemon.
    #[test]
    fn external_surface_graphics_roundtrip_matches_herdr_shapes() {
        let key = SurfaceGraphicsAssetKey {
            source: SurfaceGraphicsSource::Terminal {
                target: SurfaceGraphicsTarget::Pane {
                    pane_id: "p1".into(),
                },
                image_id: 7,
            },
            image_width: 4,
            image_height: 2,
            format: SurfaceGraphicsFormat::Rgb,
            data_len: 24,
            data_fingerprint: 42,
        };
        let frame = PaneSurfaceFrame {
            boot_id: "boot".into(),
            projection_revision: 1,
            surface_revision: 2,
            frame: empty_frame(),
            panes: Vec::new(),
            splits: Vec::new(),
            popup: None,
            graphics: SurfaceGraphicsScene {
                assets: vec![SurfaceGraphicsAsset {
                    key: key.clone(),
                    data: vec![255; 24],
                }],
                placements: vec![SurfaceGraphicsPlacement {
                    asset: key,
                    logical_placement_id: 1,
                    x: 0,
                    y: 0,
                    cols: 4,
                    rows: 2,
                    source_x: 0,
                    source_y: 0,
                    source_width: 4,
                    source_height: 2,
                    x_offset: 0,
                    y_offset: 0,
                    z: 0,
                    scrollback_offset: 0,
                }],
                retained_assets: Vec::new(),
            },
        };
        let message = ServerMessage::PaneSurface(frame);
        let bytes = bincode::serde::encode_to_vec(&message, bincode::config::standard()).unwrap();
        let (decoded, _): (ServerMessage, usize) =
            bincode::serde::decode_from_slice(&bytes, bincode::config::standard()).unwrap();
        let ServerMessage::PaneSurface(decoded_frame) = decoded else {
            panic!("roundtrip lost the PaneSurface variant");
        };
        assert_eq!(decoded_frame.graphics.assets.len(), 1);
        assert_eq!(decoded_frame.graphics.placements.len(), 1);
        assert_eq!(decoded_frame.boot_id, "boot");
    }
}
