use std::io::{Read, Write};

use serde::{Deserialize, Serialize};

pub(crate) fn write_message<W: Write, M: Serialize>(writer: &mut W, msg: &M) -> Result<(), String> {
    let payload = bincode::serde::encode_to_vec(msg, bincode::config::standard())
        .map_err(|err| err.to_string())?;
    let len = u32::try_from(payload.len()).map_err(|_| "payload too large".to_string())?;
    writer
        .write_all(&len.to_le_bytes())
        .map_err(|err| err.to_string())?;
    writer.write_all(&payload).map_err(|err| err.to_string())?;
    writer.flush().map_err(|err| err.to_string())
}

pub(crate) fn read_message<R: Read, M: for<'de> Deserialize<'de>>(
    reader: &mut R,
    max_frame_size: usize,
) -> Result<M, String> {
    let mut len_buf = [0u8; 4];
    reader
        .read_exact(&mut len_buf)
        .map_err(|err| err.to_string())?;
    let len = u32::from_le_bytes(len_buf) as usize;
    if len > max_frame_size {
        return Err(format!("frame size {len} exceeds maximum {max_frame_size}"));
    }
    let mut payload = vec![0u8; len];
    reader
        .read_exact(&mut payload)
        .map_err(|err| err.to_string())?;
    let (msg, consumed) = bincode::serde::decode_from_slice(&payload, bincode::config::standard())
        .map_err(|err| err.to_string())?;
    if consumed != len {
        return Err("trailing bytes in frame".into());
    }
    Ok(msg)
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum RenderEncoding {
    SemanticFrame,
    TerminalAnsi,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientKeybindings {
    Server,
    Local { keys_toml: String },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientLaunchMode {
    App,
    /// Full app client eligible for audited local direct graphics.
    /// A web client does not use local graphics, so this variant only needs
    /// to deserialize correctly. Added in protocol 20+.
    AppDirectGraphics,
    TerminalAttach,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientMessage {
    Hello {
        version: u32,
        cols: u16,
        rows: u16,
        cell_width_px: u32,
        cell_height_px: u32,
        requested_encoding: RenderEncoding,
        keybindings: ClientKeybindings,
        launch_mode: ClientLaunchMode,
    },
    Input {
        data: Vec<u8>,
    },
    ClipboardImage {
        extension: String,
        data: Vec<u8>,
    },
    Resize {
        cols: u16,
        rows: u16,
        cell_width_px: u32,
        cell_height_px: u32,
    },
    Detach,
    AttachTerminal {
        terminal_id: String,
        takeover: bool,
    },
    AttachScroll {
        source: AttachScrollSource,
        direction: AttachScrollDirection,
        lines: u16,
        column: Option<u16>,
        row: Option<u16>,
        modifiers: u8,
    },
    InputEvents {
        events: Vec<ClientInputEvent>,
    },
    /// Switch this connection into read-only terminal observe mode.
    /// Added in protocol 20+.
    ObserveTerminal {
        target: String,
    },
    /// Switch this connection into writable terminal control mode.
    /// Added in protocol 20+.
    ControlTerminal {
        target: String,
        takeover: bool,
    },
    /// Result of a Herdr-owned direct Kitty transmission.
    /// Added in protocol 20+ (graphics streaming).
    GraphicsTransmissionResult {
        transfer_id: u64,
        image_id: u32,
        success: bool,
    },
    /// One confirmed SGR 1016 mouse report with read-time host geometry.
    /// Added in protocol 20+ (graphics streaming).
    InputPixels {
        data: Vec<u8>,
        cols: u16,
        rows: u16,
        width_px: u32,
        height_px: u32,
    },
    /// The direct command was written and flushed.
    /// Added in protocol 20+ (graphics streaming).
    GraphicsTransmissionStarted {
        transfer_id: u64,
        image_id: u32,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum AttachScrollDirection {
    Up,
    Down,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum AttachScrollSource {
    Wheel,
    PageKey { input: Vec<u8> },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientInputEvent {
    Key {
        code: ClientKeyCode,
        modifiers: u8,
        kind: ClientKeyKind,
        /// Key repeat count from the host terminal. Added in protocol 19.
        repeat_count: u16,
        /// Text generated by this key event, if any. Added in protocol 19.
        generated_text: Option<String>,
        /// Input source metadata. Added in protocol 19.
        source: ClientKeySource,
    },
    /// Committed text (replaces the old `Text { codepoint }` variant from
    /// protocol 18). Added in protocol 19.
    TextCommit(String),
    Mouse {
        kind: ClientMouseKind,
        column: u16,
        row: u16,
        modifiers: u8,
    },
    Paste {
        text: String,
    },
    FocusGained,
    FocusLost,
}

/// Source of a key event. A web client always synthesizes keys, so the other
/// variants only need to deserialize. Added in protocol 19.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientKeySource {
    Synthesized,
    Vt { bytes: Vec<u8> },
    WindowsConsole { record: WindowsKeyRecord },
}

/// Wire-compatible mirror of herdr's `input::WindowsKeyRecord` for
/// deserializing `ClientKeySource::WindowsConsole`. A web client never
/// produces this but must accept it from Windows backends.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct WindowsKeyRecord {
    pub(crate) key_down: bool,
    pub(crate) repeat_count: u16,
    pub(crate) virtual_key_code: u16,
    pub(crate) virtual_scan_code: u16,
    pub(crate) unicode: u16,
    pub(crate) control_key_state: u32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientKeyKind {
    Press,
    Repeat,
    Release,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientKeyCode {
    Backspace,
    Enter,
    Left,
    Right,
    Up,
    Down,
    Home,
    End,
    PageUp,
    PageDown,
    Tab,
    BackTab,
    Delete,
    Insert,
    Esc,
    Char(char),
    F(u8),
    Null,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientMouseButton {
    Left,
    Right,
    Middle,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ClientMouseKind {
    Down(ClientMouseButton),
    Up(ClientMouseButton),
    Drag(ClientMouseButton),
    Moved,
    ScrollUp,
    ScrollDown,
    ScrollLeft,
    ScrollRight,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct CellData {
    symbol: String,
    fg: u32,
    bg: u32,
    modifier: u16,
    skip: bool,
    hyperlink: Option<u32>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct CursorState {
    x: u16,
    y: u16,
    visible: bool,
    #[serde(default)]
    shape: u8,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct FrameData {
    cells: Vec<CellData>,
    width: u16,
    height: u16,
    cursor: Option<CursorState>,
    hyperlinks: Vec<String>,
    graphics: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct TerminalFrame {
    pub(crate) seq: u64,
    pub(crate) width: u16,
    pub(crate) height: u16,
    pub(crate) full: bool,
    pub(crate) bytes: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum NotifyKind {
    Sound,
    Toast,
    SystemToast,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum ServerMessage {
    Welcome {
        version: u32,
        encoding: RenderEncoding,
        error: Option<String>,
    },
    Frame(FrameData),
    Terminal(TerminalFrame),
    Graphics {
        bytes: Vec<u8>,
    },
    ServerShutdown {
        reason: Option<String>,
    },
    Notify {
        kind: NotifyKind,
        message: String,
        body: Option<String>,
    },
    Clipboard {
        data: String,
    },
    WindowTitle {
        title: Option<String>,
    },
    ReloadSoundConfig,
    MouseCapture {
        enabled: bool,
        /// True only while the focused pane requests DEC SGR pixel mode 1016.
        /// Added in protocol 20+ (graphics streaming). A web client does not
        /// act on it, so we only need to deserialize it.
        #[serde(default)]
        sgr_pixels: bool,
    },
    /// Whether the focused terminal requests Kitty report-all keyboard input.
    /// The backend sends this so the client can adjust its input handling;
    /// a web client does not act on it, so we only need to deserialize it.
    /// Added in protocol 18.
    KittyKeyboardReportAll {
        enabled: bool,
    },
    /// Forwarded macOS prefix-mode ASCII input-source switch request. The
    /// backend sends this to the foreground client so it can swap the host
    /// keyboard layout; a web client has no host keyboard to switch, so we
    /// only need to deserialize it without acting on it. Added in protocol 16.
    PrefixInputSource {
        active: bool,
    },
    /// Ring the foreground client's outer terminal for pane-originated BEL
    /// characters. A web client can play a sound or visual bell. Added in
    /// protocol 20.
    TerminalBell {
        count: u16,
    },
    /// One validated Herdr-owned Kitty regular-file RGBA transmission.
    /// A web client does not process local graphics files, so this only
    /// needs to deserialize. Added in protocol 20+ (graphics streaming).
    GraphicsFile {
        path: String,
        expected_len: u64,
        image_id: u32,
        transfer_id: u64,
        leading: Vec<u8>,
        control: String,
    },
    /// Suppress a direct command that expired before terminal delivery.
    /// Added in protocol 20+ (graphics streaming).
    GraphicsTransmissionRetired {
        transfer_id: u64,
        image_id: u32,
    },
}
