//! Guard for the test env-lock convention (PR #240 follow-up).
//!
//! Env vars are process-global and cargo test binaries run tests on parallel
//! threads, so any test that writes env vars must serialize against a shared
//! lock: `crate::tests::env_lock` (bin target) or `crate::test_env_lock`
//! (lib target), usually via a module-local wrapper fn. PR #240 unified the
//! last private lock islands after a first-build 3-test flake. This module
//! keeps that convention from regressing: it runs as a normal `#[test]`, so
//! `cargo test` (locally and in CI) enforces it on every change.
//!
//! How it works: every `src/**/*.rs`, `tests/**/*.rs`, and `build.rs` file is
//! parsed with syn (AST, so string literals and comments never trip it) and
//! the rules below are checked.
//!
//! R1 - every fn whose body calls something named `set_var`/`remove_var` must
//! also acquire a lock named `env_lock`/`lock_env`/`home_lock`/
//! `test_env_lock` within the same fn body (closures inside the body count,
//! e.g. the spawn_blocking env redirect in the composer parity e2e). Fns that
//! legitimately cannot take the lock (helpers running under the caller's
//! guard, evidence-verified race-free tests, runtime code) live in
//! `ALLOWLIST` with written evidence.
//!
//! R3 - no static unit mutex (`Mutex<()>`, including `OnceLock<Mutex<()>>`)
//! may exist outside the allowed lock fns, and an allowed lock fn may own
//! exactly one such static. In `src/` the only allowed owners are the two
//! canonical lock factories; in `tests/` each integration binary owns one
//! lock convention of its own, so a fn whose name is in `LOCK_NAMES` may own
//! one (at most one per file: two islands in the same binary can race). A
//! private island lets its holder race every other module's env window in
//! the same test binary, which is exactly the PR #240 bug class, so R3 bans
//! the island itself rather than trusting wrapper fns to point at a
//! canonical lock.
//!
//! Stale entries: an `ALLOWLIST` entry that no longer matches a real
//! env-writing fn fails the guard, so the evidence cannot silently rot.
//!
//! Known blind spots, accepted as residual risk:
//! - Env writes generated by macros are token streams that syn does not
//!   expand, so they are invisible here. No such writes exist today; every
//!   current write is a direct call.
//! - Cross-process writes (a spawned server process or another test binary
//!   reading env while a test mutates it) cannot be serialized by any
//!   in-process mutex. No such race has ever been observed in this repo; the
//!   fix would be per-process env isolation (passing env explicitly to
//!   spawned servers or serializing whole binaries), out of scope here.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use syn::visit::Visit;
use syn::{Expr, ExprCall, File, Item, ItemFn};

/// Call names that count as acquiring the shared env lock.
const LOCK_NAMES: [&str; 4] = ["env_lock", "lock_env", "home_lock", "test_env_lock"];

/// Call names that count as an env write.
const ENV_WRITE_NAMES: [&str; 2] = ["set_var", "remove_var"];

/// (file, fn, written evidence) for env-writing fns exempted from R1.
/// Keep entries sorted by file. Every entry must match a real env-writing fn
/// or the guard reports it as stale.
const ALLOWLIST: &[(&str, &str, &str)] = &[
    (
        "src/backend_client.rs",
        "restore_env_var",
        "helper restores under the caller's env_lock guard; std sync Mutex is not reentrant so locking here would deadlock",
    ),
    (
        "src/builtin_backend.rs",
        "builtin_pane_child_env_advertises_kitty_hint_and_scrubs_inherited_kitty_id",
        "pane spawn force-inserts TERM_PROGRAM=ghostty and scrubs KITTY_WINDOW_ID before the child env is built, so a leaked value cannot mislead anything (PR #240 worst-case export run: bin suite 602/0)",
    ),
    (
        "src/builtin_backend.rs",
        "builtin_panes_advertise_kitty_env_and_scrub_inherited_hints",
        "same spawn-site scrub covers the child PTY; validated with worst-case inherited values in the PR #240 audit",
    ),
    (
        "src/main.rs",
        "main",
        "runtime entry point: parses --verbose once at startup, never runs inside a cargo test binary",
    ),
    (
        "src/terminal_hub.rs",
        "replay_cap_reads_env_override",
        "HERDR_REPLAY_CAP_BYTES feeds only replay_cap() and no other test reads or writes it, so nothing can observe the window (verified in the PR #240 audit)",
    ),
    (
        "src/tui/theme.rs",
        "restore_env_var",
        "helper restores under the caller's env_lock guard; std sync Mutex is not reentrant so locking here would deadlock",
    ),
    (
        "src/tui_parity_e2e_tests.rs",
        "drop",
        "EnvRedirectGuard::drop restores XDG_CONFIG_HOME while its creator still holds crate::tests::lock_env()",
    ),
];

/// The only fns allowed to own a static unit mutex: the two canonical lock
/// factories. Any other unit-mutex static is a private lock island (R3).
const CANONICAL_LOCK_FNS: [(&str, &str); 2] = [
    ("src/lib.rs", "test_env_lock"),
    ("src/tests.rs", "env_lock"),
];

/// In `tests/` each integration binary owns one lock convention of its own
/// (there is no crate root to hang it on), so any fn whose name is in
/// `LOCK_NAMES` may own a static unit mutex, at most one per file: two
/// islands in the same binary can race each other.
fn is_tests_lock_fn(file: &str, name: &str) -> bool {
    file.starts_with("tests/") && LOCK_NAMES.contains(&name)
}

/// Per-fn facts collected from the AST.
#[derive(Default)]
struct FnScan {
    env_writes: Vec<String>,
    lock_acquired: bool,
    unit_mutex_statics: Vec<String>,
}

impl<'ast> Visit<'ast> for FnScan {
    fn visit_expr_call(&mut self, call: &'ast ExprCall) {
        if let Expr::Path(path) = &*call.func {
            let last = path
                .path
                .segments
                .last()
                .map(|seg| seg.ident.to_string())
                .unwrap_or_default();
            if ENV_WRITE_NAMES.contains(&last.as_str()) {
                self.env_writes.push(last.clone());
            }
            if LOCK_NAMES.contains(&last.as_str()) {
                self.lock_acquired = true;
            }
        }
        syn::visit::visit_expr_call(self, call);
    }

    fn visit_item_static(&mut self, stat: &'ast syn::ItemStatic) {
        if ty_contains_unit_mutex(&stat.ty) {
            self.unit_mutex_statics.push(stat.ident.to_string());
        }
        syn::visit::visit_item_static(self, stat);
    }
}

/// True when the type mentions `Mutex<()>` (or an alias like `StdMutex<()>`),
/// including through wrappers such as `OnceLock<StdMutex<()>>`. Structural
/// walk, no token stringification needed.
fn ty_contains_unit_mutex(ty: &syn::Type) -> bool {
    match ty {
        syn::Type::Path(path) => {
            let Some(last) = path.path.segments.last() else {
                return false;
            };
            let syn::PathArguments::AngleBracketed(args) = &last.arguments else {
                return false;
            };
            let type_args: Vec<&syn::Type> = args
                .args
                .iter()
                .filter_map(|arg| match arg {
                    syn::GenericArgument::Type(inner) => Some(inner),
                    _ => None,
                })
                .collect();
            let mutex_like = matches!(last.ident.to_string().as_str(), "Mutex" | "StdMutex");
            let unit_arg = type_args
                .iter()
                .any(|inner| matches!(inner, syn::Type::Tuple(tuple) if tuple.elems.is_empty()));
            if mutex_like && unit_arg {
                return true;
            }
            type_args.iter().any(|inner| ty_contains_unit_mutex(inner))
        }
        syn::Type::Reference(r) => ty_contains_unit_mutex(&r.elem),
        syn::Type::Paren(p) => ty_contains_unit_mutex(&p.elem),
        syn::Type::Group(g) => ty_contains_unit_mutex(&g.elem),
        syn::Type::Tuple(t) => t.elems.iter().any(ty_contains_unit_mutex),
        syn::Type::Array(a) => ty_contains_unit_mutex(&a.elem),
        syn::Type::Slice(s) => ty_contains_unit_mutex(&s.elem),
        syn::Type::Ptr(p) => ty_contains_unit_mutex(&p.elem),
        _ => false,
    }
}

/// One scanned fn (or impl/trait method) with its collected facts.
struct ScannedFn {
    file: String,
    name: String,
    env_writes: Vec<String>,
    lock_acquired: bool,
    unit_mutex_statics: Vec<String>,
}

/// Unit-mutex statics declared at module top level, outside any fn.
struct TopLevelStatic {
    file: String,
    name: String,
}

fn scan_fn(file: &str, name: &str, func: &ItemFn) -> ScannedFn {
    let mut scan = FnScan::default();
    scan.visit_item_fn(func);
    ScannedFn {
        file: file.to_string(),
        name: name.to_string(),
        env_writes: scan.env_writes,
        lock_acquired: scan.lock_acquired,
        unit_mutex_statics: scan.unit_mutex_statics,
    }
}

fn walk_items(
    file: &str,
    items: &[Item],
    fns: &mut Vec<ScannedFn>,
    statics: &mut Vec<TopLevelStatic>,
) {
    for item in items {
        match item {
            Item::Fn(func) => {
                let name = func.sig.ident.to_string();
                fns.push(scan_fn(file, &name, func));
            }
            Item::Impl(imp) => {
                for impl_item in &imp.items {
                    if let syn::ImplItem::Fn(method) = impl_item {
                        let name = method.sig.ident.to_string();
                        let mut scan = FnScan::default();
                        scan.visit_impl_item_fn(method);
                        fns.push(ScannedFn {
                            file: file.to_string(),
                            name,
                            env_writes: scan.env_writes,
                            lock_acquired: scan.lock_acquired,
                            unit_mutex_statics: scan.unit_mutex_statics,
                        });
                    }
                }
            }
            Item::Trait(trait_) => {
                for trait_item in &trait_.items {
                    if let syn::TraitItem::Fn(method) = trait_item {
                        if method.default.is_some() {
                            let name = method.sig.ident.to_string();
                            let mut scan = FnScan::default();
                            scan.visit_trait_item_fn(method);
                            fns.push(ScannedFn {
                                file: file.to_string(),
                                name,
                                env_writes: scan.env_writes,
                                lock_acquired: scan.lock_acquired,
                                unit_mutex_statics: scan.unit_mutex_statics,
                            });
                        }
                    }
                }
            }
            Item::Mod(module) => {
                if let Some((_, inner)) = &module.content {
                    walk_items(file, inner, fns, statics);
                }
            }
            Item::Static(stat) if ty_contains_unit_mutex(&stat.ty) => {
                statics.push(TopLevelStatic {
                    file: file.to_string(),
                    name: stat.ident.to_string(),
                });
            }
            _ => {}
        }
    }
}

fn collect_rs_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries =
        std::fs::read_dir(dir).unwrap_or_else(|err| panic!("read_dir {}: {err}", dir.display()));
    for entry in entries {
        let entry = entry.expect("read_dir entry");
        let path = entry.path();
        if path.is_dir() {
            collect_rs_files(&path, out);
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            out.push(path);
        }
    }
}

/// Path relative to the package root, matching ALLOWLIST keys ("src/x.rs").
fn rel_path(file: &Path) -> String {
    file.strip_prefix(env!("CARGO_MANIFEST_DIR"))
        .unwrap_or(file)
        .to_string_lossy()
        .replace('\\', "/")
}

#[test]
fn test_env_convention_is_enforced() {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mut files = Vec::new();
    for dir in ["src", "tests"] {
        let mut scoped = Vec::new();
        collect_rs_files(&manifest.join(dir), &mut scoped);
        assert!(
            !scoped.is_empty(),
            "no rust sources under {}",
            manifest.join(dir).display()
        );
        files.extend(scoped);
    }
    let build_rs = manifest.join("build.rs");
    if build_rs.is_file() {
        files.push(build_rs);
    }
    files.sort();

    let mut fns = Vec::new();
    let mut statics = Vec::new();
    for file in &files {
        let source = std::fs::read_to_string(file)
            .unwrap_or_else(|err| panic!("read {}: {err}", file.display()));
        let parsed: File = syn::parse_file(&source).unwrap_or_else(|err| {
            panic!(
                "{} does not parse; the guard is blind to it: {err}",
                file.display()
            )
        });
        let rel = rel_path(file);
        walk_items(&rel, &parsed.items, &mut fns, &mut statics);
    }

    let mut violations = Vec::new();

    // R1: env writes need a lock acquisition in the same fn body, or an
    // allowlist entry with written evidence.
    let mut allowlist_used = vec![false; ALLOWLIST.len()];
    for func in &fns {
        if func.env_writes.is_empty() {
            continue;
        }
        if let Some(slot) = ALLOWLIST
            .iter()
            .position(|(file, name, _)| *file == func.file && *name == func.name)
        {
            allowlist_used[slot] = true;
            continue;
        }
        if func.lock_acquired {
            continue;
        }
        violations.push(format!(
            "  [R1] {} fn `{}` writes env ({}) without acquiring a shared env lock",
            func.file,
            func.name,
            func.env_writes.join(", ")
        ));
        violations.push(
            "       fix: take the lock at fn start (`let _guard = env_lock();` via your module's wrapper over crate::tests::env_lock / crate::test_env_lock), or, if the mutation is provably race-free, add an entry to ALLOWLIST in src/test_env_guard.rs with the evidence".to_string()
        );
    }

    // Stale allowlist entries: the evidence must keep matching reality.
    for (slot, (file, name, _)) in ALLOWLIST.iter().enumerate() {
        if !allowlist_used[slot] {
            violations.push(format!(
                "  [stale] ALLOWLIST entry ({file}, `{name}`) no longer matches an env-writing fn; remove it, or update it if the fn was renamed"
            ));
        }
    }

    // R3: private unit-mutex lock islands.
    let mut tests_lock_owners: HashMap<String, String> = HashMap::new();
    for func in &fns {
        if func.unit_mutex_statics.is_empty() {
            continue;
        }
        let exempted = CANONICAL_LOCK_FNS
            .iter()
            .any(|(file, name)| *file == func.file && *name == func.name)
            || is_tests_lock_fn(&func.file, &func.name);
        if exempted && func.unit_mutex_statics.len() > 1 {
            violations.push(format!(
                "  [R3] {} fn `{}` declares {} unit-mutex statics {}; an exempted lock fn must own exactly one: a second island inside it lets two env windows race without serializing. Remove the extra static(s)",
                func.file,
                func.name,
                func.unit_mutex_statics.len(),
                func.unit_mutex_statics.join(", ")
            ));
            continue;
        }
        if CANONICAL_LOCK_FNS
            .iter()
            .any(|(file, name)| *file == func.file && *name == func.name)
        {
            continue;
        }
        if is_tests_lock_fn(&func.file, &func.name) {
            let owner = tests_lock_owners
                .entry(func.file.clone())
                .or_insert_with(|| func.name.clone());
            if *owner == func.name {
                continue;
            }
            violations.push(format!(
                "  [R3] {} fn `{}` declares a second unit-mutex lock fn in a binary that already has `{owner}`; two islands in the same test binary can race each other. Merge them into one per-file lock fn",
                func.file, func.name
            ));
            continue;
        }
        violations.push(format!(
            "  [R3] {} fn `{}` declares private unit-mutex static(s) {}; module-private env locks let cross-module env windows race (the PR #240 bug class). Reuse crate::tests::env_lock / crate::test_env_lock",
            func.file,
            func.name,
            func.unit_mutex_statics.join(", ")
        ));
    }
    for stat in &statics {
        violations.push(format!(
            "  [R3] {} static `{}` is a private unit-mutex env lock outside the canonical lock fns; reuse crate::tests::env_lock / crate::test_env_lock",
            stat.file, stat.name
        ));
    }

    assert!(
        violations.is_empty(),
        "test env-lock convention violations:\n{}",
        violations.join("")
    );
}
