//! Guard for the test env-lock convention (PR #240 follow-up).
//!
//! Env vars are process-global and cargo test binaries run tests on parallel
//! threads, so any test that writes env vars must serialize against a shared
//! lock: `crate::tests::env_lock` (bin target) or `crate::test_env_lock`
//! (lib target), usually via a module-local wrapper fn. PR #240 unified the
//! last private lock islands after a first-build 3-test flake. This module
//! keeps that convention from regressing: it runs as a normal `#[test]`, so
//! `cargo test` (locally and in CI) enforces it on every change.
//!
//! How it works: every `src/**/*.rs`, `tests/**/*.rs`, and `build.rs` file is
//! parsed with syn (AST, so string literals and comments never trip it) and
//! the rules below are checked.
//!
//! R1 - every fn whose body calls something named `set_var`/`remove_var` must
//! also acquire a lock named `env_lock`/`lock_env`/`home_lock`/
//! `test_env_lock` within the same fn body (closures inside the body count,
//! e.g. the spawn_blocking env redirect in the composer parity e2e). Fns that
//! legitimately cannot take the lock (helpers running under the caller's
//! guard, evidence-verified race-free tests, runtime code) live in
//! `ALLOWLIST` with written evidence.
//!
//! R3 - no static unit mutex (`Mutex<()>`, including `OnceLock<Mutex<()>>`)
//! may exist outside the allowed lock fns, and an allowed lock fn may own
//! exactly one such static. In `src/` the only allowed owners are the two
//! canonical lock factories; in `tests/` each integration binary owns one
//! lock convention of its own, so a fn whose name is in `LOCK_NAMES` may own
//! one (at most one per file: two islands in the same binary can race). A
//! private island lets its holder race every other module's env window in
//! the same test binary, which is exactly the PR #240 bug class, so R3 bans
//! the island itself rather than trusting wrapper fns to point at a
//! canonical lock.
//!
//! Stale entries: an `ALLOWLIST` entry that no longer matches a real
//! env-writing fn fails the guard, so the evidence cannot silently rot.
//!
//! R1 coverage is order- and scope-sensitive: the lock must be acquired
//! before the first env write, in the same closure scope. A lock guard
//! taken in a fn body does not cover env writes inside closures or async
//! blocks in it (spawned threads and deferred closures can outlive the
//! guard), and a write before the lock call races the window between fn
//! start and acquisition. Closures that write env must take the lock in
//! their own body; a closure defined before the lock and called after it
//! is covered only via the allowlist (flow-insensitive residual FP).
//! Locks inside conditionally-executed blocks (`if`/`match` arms) still
//! cover later writes syntactically: the approximation is order-sensitive,
//! not flow-sensitive (same residual as before, unchanged in class).
//!
//! Known blind spots, accepted as residual risk:
//! - A `use crate::tests::*;` glob import brings `env_lock` in unqualified,
//!   and glob-import recording is out of scope for the resolver, so the
//!   call stays unprovable and fires R1 even when genuine. No real code
//!   glob-imports the tests module; spell the path out or allowlist.
//! - Env writes generated by macros are token streams that syn does not
//!   expand, so they are invisible here. No such writes exist today; every
//!   current write is a direct call.
//! - Method-call lock acquisition resolves the receiver only for plain
//!   shapes (`self`, a local bound to a unit-struct constructor). Any other
//!   receiver (field, call result, re-binding) is unprovable and fires R1;
//!   real code uses plain wrapper-fn calls, so no allowlist entry is needed.
//! - Cross-process writes (a spawned server process or another test binary
//!   reading env while a test mutates it) cannot be serialized by any
//!   in-process mutex. No such race has ever been observed in this repo; the
//!   fix would be per-process env isolation (passing env explicitly to
//!   spawned servers or serializing whole binaries), out of scope here.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use syn::visit::Visit;
use syn::{Expr, ExprCall, File, Item, ItemFn};

/// Call names that count as acquiring the shared env lock.
const LOCK_NAMES: [&str; 4] = ["env_lock", "lock_env", "home_lock", "test_env_lock"];

/// Name shapes that count as an env write: `std::env::set_var`, a bare
/// `set_var`, a `use std::env::set_var` import called bare, or the same
/// bound to a local (`let write = std::env::set_var;`). A rename
/// (`use std::env::set_var as sv`) makes the call invisible, so any rename
/// of an env-write import is itself refused: the convention is plain names.
const ENV_WRITE_NAMES: [&str; 2] = ["set_var", "remove_var"];

/// (file, fn, written evidence) for env-writing fns exempted from R1.
/// Keep entries sorted by file. Every entry must match a real env-writing fn
/// or the guard reports it as stale.
const ALLOWLIST: &[(&str, &str, &str)] = &[
    (
        "src/backend_client.rs",
        "restore_env_var",
        "helper restores under the caller's env_lock guard; std sync Mutex is not reentrant so locking here would deadlock",
    ),
    (
        "src/builtin_backend.rs",
        "builtin_pane_child_env_advertises_kitty_hint_and_scrubs_inherited_kitty_id",
        "pane spawn force-inserts TERM_PROGRAM=ghostty and scrubs KITTY_WINDOW_ID before the child env is built, so a leaked value cannot mislead anything (PR #240 worst-case export run: bin suite 602/0)",
    ),
    (
        "src/builtin_backend.rs",
        "builtin_panes_advertise_kitty_env_and_scrub_inherited_hints",
        "same spawn-site scrub covers the child PTY; validated with worst-case inherited values in the PR #240 audit",
    ),
    (
        "src/main.rs",
        "main",
        "runtime entry point: parses --verbose once at startup, never runs inside a cargo test binary",
    ),
    (
        "src/terminal_hub.rs",
        "replay_cap_reads_env_override",
        "HERDR_REPLAY_CAP_BYTES feeds only replay_cap() and no other test reads or writes it, so nothing can observe the window (verified in the PR #240 audit)",
    ),
    (
        "src/tui/theme.rs",
        "restore_env_var",
        "helper restores under the caller's env_lock guard; std sync Mutex is not reentrant so locking here would deadlock",
    ),
    (
        "src/tui_parity_e2e_tests.rs",
        "drop",
        "EnvRedirectGuard::drop restores XDG_CONFIG_HOME while its creator still holds crate::tests::lock_env()",
    ),
];

/// The only fns allowed to own a static unit mutex: the two canonical lock
/// factories. Any other unit-mutex static is a private lock island (R3).
const CANONICAL_LOCK_FNS: [(&str, &str); 2] = [
    ("src/lib.rs", "test_env_lock"),
    ("src/tests.rs", "env_lock"),
];

/// In `tests/` each integration binary owns one lock convention of its own
/// (there is no crate root to hang it on), so any fn whose name is in
/// `LOCK_NAMES` may own a static unit mutex, at most one per file: two
/// islands in the same binary can race each other.
fn is_tests_lock_fn(file: &str, name: &str) -> bool {
    file.starts_with("tests/") && LOCK_NAMES.contains(&name)
}

/// Per-fn facts collected from the AST.
#[derive(Default)]
struct FnScan {
    env_writes: Vec<String>,
    /// Last path segments of fns called with a LOCK_NAMES name, plus the
    /// qualifier path (`crate::tests::env_lock` stores `crate::tests`).
    lock_calls: Vec<(String, String)>,
    /// Ordered scan events (source order): env writes and lock
    /// acquisitions with the closure depth at which they occur, plus
    /// closure-enter markers. R1 coverage is order-sensitive: a write is
    /// only covered by a lock acquired earlier in the SAME closure scope,
    /// because a lock guard held by the parent fn does not cover writes
    /// made by a spawned thread or a deferred closure body.
    events: Vec<ScanEvent>,
    /// Current closure nesting depth: closures and async blocks get their
    /// own scope. A lock in the parent body does not cover a write inside
    /// a closure body that may run after the guard is dropped.
    closure_depth: usize,
    unit_mutex_statics: Vec<String>,
    /// Local names bound to env-write paths inside this fn, so calls through
    /// the binding still count (`let write = std::env::set_var;`). Aliases of
    /// a binding (`let w1 = w0;`) resolve transitively.
    env_write_bindings: Vec<String>,
    /// Crate-wide `type` aliases (`type M = Mutex<()>;`), cloned per scan so
    /// static types can resolve through them.
    aliases: HashMap<String, syn::Path>,
    /// Names of locals bound to a cast of an env-write path (`let w =
    /// set_var as fn(..)`), plus aliases of those names, so chained bindings
    /// (`let w2 = w;`) still count as env writes.
    cast_write_bindings: Vec<String>,
    /// Local names bound to lock-fn paths in this fn (`let lock = lock_env;`),
    /// mapping to the bound path's (qualifier, fn name) so calls through the
    /// binding still count as lock acquisitions.
    lock_bindings: HashMap<String, (String, String)>,
    /// Local names bound to any path in this fn (`let x = foo;`), so a
    /// shadowing call (`let env_lock = not_a_lock; env_lock()`) cannot
    /// borrow the genuine fn's reputation.
    locals: Vec<String>,
    /// Receiver local name -> receiver type name (`let holder = Holder;`),
    /// so method calls (`holder.lock_env()`) resolve to that type's impl.
    receiver_types: HashMap<String, String>,
    /// Impl type name when scanning a method (`impl Wrapper { .. }`), so
    /// `Self::lock_env()` resolves to the impl's own lock fns.
    impl_type: Option<String>,
}

/// True when the path names an env write directly (last segment is one of
/// `ENV_WRITE_NAMES`), covering qualified and imported-bare forms alike.
fn path_contains_env_write(path: &syn::Path) -> bool {
    path.segments
        .last()
        .map(|seg| ENV_WRITE_NAMES.contains(&seg.ident.to_string().as_str()))
        .unwrap_or(false)
}

impl FnScan {
    /// Record a lock-name call: into the flat list (resolution) and the
    /// ordered event stream (R1 coverage check).
    fn record_lock(&mut self, qual: String, name: String) {
        self.lock_calls.push((qual.clone(), name.clone()));
        self.events.push(ScanEvent::Lock(qual, name));
    }

    /// True when the call target references an env write either directly
    /// (`std::env::set_var`, bare `set_var` via a `use std::env::set_var`
    /// import) or through a local binding of this fn
    /// (`let write = std::env::set_var;`).
    fn expr_referencing_env_write(&self, path: &syn::ExprPath) -> bool {
        let last = path
            .path
            .segments
            .last()
            .map(|seg| seg.ident.to_string())
            .unwrap_or_default();
        ENV_WRITE_NAMES.contains(&last.as_str())
            || self.env_write_bindings.iter().any(|b| b == &last)
            || self.cast_write_bindings.iter().any(|b| b == &last)
    }
}

impl<'ast> Visit<'ast> for FnScan {
    fn visit_expr_call(&mut self, call: &'ast ExprCall) {
        // Parenthesized call target `(std::env::set_var)(..)`: unwrap so the
        // write is still seen.
        let target = match &*call.func {
            Expr::Path(path) => Some(path),
            Expr::Paren(paren) => match &*paren.expr {
                Expr::Path(path) => Some(path),
                _ => None,
            },
            _ => None,
        };
        if let Some(path) = target {
            let last = path
                .path
                .segments
                .last()
                .map(|seg| seg.ident.to_string())
                .unwrap_or_default();
            if self.expr_referencing_env_write(path) {
                self.env_writes.push(last.clone());
                self.events.push(ScanEvent::Write);
            }
            if LOCK_NAMES.contains(&last.as_str()) {
                if let Some((qual, name)) = self.lock_bindings.get(&last).cloned() {
                    // A local binding of a lock path whose name collides with
                    // a LOCK_NAMES name (`let env_lock = lock_env;`): resolve
                    // as the bound path.
                    self.record_lock(qual, name);
                } else if self.locals.contains(&last) {
                    // A local shadowing a lock-name path but bound to
                    // something else (`let env_lock = not_a_lock;
                    // env_lock();`): the call cannot borrow the genuine fn's
                    // reputation. Unprovable marker.
                    self.record_lock("<method>".to_string(), last);
                } else {
                    let qualifier = path
                        .path
                        .segments
                        .iter()
                        .rev()
                        .skip(1)
                        .map(|seg| seg.ident.to_string())
                        .collect::<Vec<_>>()
                        .into_iter()
                        .rev()
                        .collect::<Vec<_>>()
                        .join("::");
                    // `Self::lock_env()` inside `impl Wrapper`: resolve to
                    // the impl's own type. Outside an impl (trait default)
                    // the type is unknown: unprovable marker.
                    let qualifier = if qualifier == "Self" {
                        self.impl_type
                            .clone()
                            .unwrap_or_else(|| "<method>".to_string())
                    } else {
                        qualifier
                    };
                    self.record_lock(qualifier, last);
                }
            } else if let Some((qual, name)) = self.lock_bindings.get(&last).cloned() {
                // Call through a local lock binding: `let lock = lock_env;`
                // `lock()`. Resolve as the bound path.
                self.record_lock(qual, name);
            } else if self.locals.contains(&last) {
                // A local shadowing a lock-name path but bound to something
                // else (`let env_lock = not_a_lock; env_lock();`): the call
                // cannot borrow the genuine fn's reputation.
                self.record_lock("<method>".to_string(), last);
            }
        }
        syn::visit::visit_expr_call(self, call);
    }

    fn visit_expr_method_call(&mut self, call: &'ast syn::ExprMethodCall) {
        // `holder.lock_env()`: method-syntax lock acquisition. The receiver
        // is resolved when possible: `self` -> this impl's type, a local
        // bound to a unit-struct constructor (`let holder = Holder;`) -> that
        // type. Any other receiver (field, call result, unknown local) is
        // unprovable and records a marker that never resolves.
        if LOCK_NAMES.contains(&call.method.to_string().as_str()) {
            let receiver = match &*call.receiver {
                syn::Expr::Path(path) if path.path.segments.len() == 1 => {
                    Some(path.path.segments[0].ident.to_string())
                }
                _ => None,
            };
            let qualifier = match receiver.as_deref() {
                Some("self") => self
                    .impl_type
                    .clone()
                    .unwrap_or_else(|| "<method>".to_string()),
                Some(local) => self
                    .receiver_types
                    .get(local)
                    .cloned()
                    .unwrap_or_else(|| "<method>".to_string()),
                None => "<method>".to_string(),
            };
            self.record_lock(qualifier, call.method.to_string());
        }
        syn::visit::visit_expr_method_call(self, call);
    }

    fn visit_expr_closure(&mut self, closure: &'ast syn::ExprClosure) {
        // A closure body may run after the parent's lock guard is dropped
        // (spawned threads, deferred calls), so writes inside need a lock
        // acquired inside the closure body itself. Track the nesting depth
        // in the event stream; the R1 check requires lock-before-write at
        // the same depth.
        self.closure_depth += 1;
        self.events.push(ScanEvent::EnterClosure);
        syn::visit::visit_expr_closure(self, closure);
        self.events.push(ScanEvent::ExitClosure);
        self.closure_depth -= 1;
    }

    fn visit_expr_async(&mut self, async_block: &'ast syn::ExprAsync) {
        // Async blocks have the same deferred-execution semantics as
        // closures.
        self.closure_depth += 1;
        self.events.push(ScanEvent::EnterClosure);
        syn::visit::visit_expr_async(self, async_block);
        self.events.push(ScanEvent::ExitClosure);
        self.closure_depth -= 1;
    }

    fn visit_local(&mut self, local: &'ast syn::Local) {
        if let Some(init) = &local.init {
            if matches!(&*init.expr, syn::Expr::Path(path)
                if path_contains_env_write(&path.path))
            {
                if let syn::Pat::Ident(pat) = &local.pat {
                    self.env_write_bindings.push(pat.ident.to_string());
                }
            } else if let syn::Expr::Path(path) = &*init.expr {
                let last = path
                    .path
                    .segments
                    .last()
                    .map(|s| s.ident.to_string())
                    .unwrap_or_default();
                if let syn::Pat::Ident(pat) = &local.pat {
                    let name = pat.ident.to_string();
                    self.locals.push(name.clone());
                    if LOCK_NAMES.contains(&last.as_str()) {
                        let qualifier = path
                            .path
                            .segments
                            .iter()
                            .rev()
                            .skip(1)
                            .map(|seg| seg.ident.to_string())
                            .collect::<Vec<_>>()
                            .into_iter()
                            .rev()
                            .collect::<Vec<_>>()
                            .join("::");
                        self.lock_bindings
                            .insert(name.clone(), (qualifier, last.clone()));
                    }
                    // `let holder = Holder;` / `let h = tests::Holder;`:
                    // record the receiver type (last path segment; value
                    // paths to unit constructors end with the type name) so
                    // method calls on this local resolve to the impl.
                    self.receiver_types.insert(name.clone(), last.clone());
                    // `let w1 = w0;`: alias of an existing binding resolves
                    // transitively across all binding kinds, so chains of
                    // aliases keep the original meaning.
                    if self.env_write_bindings.contains(&last) {
                        self.env_write_bindings.push(name.clone());
                    }
                    if let Some(bound) = self.lock_bindings.get(&last).cloned() {
                        self.lock_bindings.insert(name.clone(), bound);
                    }
                    if let Some(ty) = self.receiver_types.get(&last).cloned() {
                        self.receiver_types.insert(name.clone(), ty);
                    }
                    if self.cast_write_bindings.contains(&last) {
                        self.cast_write_bindings.push(name);
                    }
                }
            } else if let syn::Expr::Cast(cast) = &*init.expr {
                // `let w = std::env::set_var as fn(..);`: the cast binds an
                // env write under a new name. Check the inner path here,
                // where the binding name is known, so no pending state can
                // go stale between casts.
                if matches!(&*cast.expr, syn::Expr::Path(path)
                    if path_contains_env_write(&path.path))
                {
                    if let syn::Pat::Ident(pat) = &local.pat {
                        self.cast_write_bindings.push(pat.ident.to_string());
                    }
                }
            }
        }
        syn::visit::visit_local(self, local);
    }

    fn visit_item_type(&mut self, ty: &'ast syn::ItemType) {
        // Fn-local `type M = Mutex<()>;` ahead of a `static S: M`: resolve
        // like crate-wide aliases.
        if let syn::Type::Path(path) = &*ty.ty {
            self.aliases.insert(ty.ident.to_string(), path.path.clone());
        }
        syn::visit::visit_item_type(self, ty);
    }

    fn visit_expr_cast(&mut self, cast: &'ast syn::ExprCast) {
        // Env writes through casts are handled in visit_local, where the
        // binding name and the cast initializer are both in hand. Nothing
        // pending here.
        syn::visit::visit_expr_cast(self, cast);
    }

    fn visit_item_use(&mut self, use_item: &'ast syn::ItemUse) {
        walk_local_use_tree(&use_item.tree, &mut self.env_write_bindings);
        syn::visit::visit_item_use(self, use_item);
    }

    fn visit_item_static(&mut self, stat: &'ast syn::ItemStatic) {
        if ty_contains_unit_mutex(&stat.ty, &self.aliases) {
            self.unit_mutex_statics.push(stat.ident.to_string());
        }
        syn::visit::visit_item_static(self, stat);
    }
}

/// One ordered scan event inside a fn body.
enum ScanEvent {
    /// An env write at the current closure depth.
    Write,
    /// A lock-name call at the current closure depth (qualifier, name).
    Lock(String, String),
    /// Entering a closure or async block: writes inside need their own
    /// lock acquisition.
    EnterClosure,
    /// Leaving a closure or async block.
    ExitClosure,
}

/// Fold a use tree inside a fn body (`use std::env::set_var as sv;`) into
/// the env-write binding names, so a call through the local alias still
/// counts as an env write. Renames of env writes are covered; plain imports
/// are already caught by the last-segment name match.
fn walk_local_use_tree(tree: &syn::UseTree, bindings: &mut Vec<String>) {
    match tree {
        syn::UseTree::Path(path) => walk_local_use_tree(&path.tree, bindings),
        syn::UseTree::Group(group) => {
            for item in &group.items {
                walk_local_use_tree(item, bindings);
            }
        }
        syn::UseTree::Rename(rename) => {
            if ENV_WRITE_NAMES.contains(&rename.ident.to_string().as_str()) {
                bindings.push(rename.rename.to_string());
            }
        }
        syn::UseTree::Name(_) | syn::UseTree::Glob(_) => {}
    }
}

/// True when the type mentions `Mutex<()>` (or an alias like `StdMutex<()>`),
/// including through wrappers such as `OnceLock<StdMutex<()>>` and through
/// `type` aliases (`type M = Mutex<()>;`). Structural walk, no token
/// stringification needed.
fn ty_contains_unit_mutex(ty: &syn::Type, aliases: &HashMap<String, syn::Path>) -> bool {
    match ty {
        syn::Type::Path(path) => {
            let Some(last) = path.path.segments.last() else {
                return false;
            };
            let syn::PathArguments::AngleBracketed(args) = &last.arguments else {
                // No type arguments: the name itself may be an alias for a
                // mutex type (`type M = Mutex<()>; static L: M`).
                let name = last.ident.to_string();
                if let Some(target) = aliases.get(&name) {
                    let resolved = syn::TypePath {
                        qself: None,
                        path: target.clone(),
                    };
                    return ty_contains_unit_mutex(&syn::Type::Path(resolved), aliases);
                }
                return false;
            };
            let type_args: Vec<&syn::Type> = args
                .args
                .iter()
                .filter_map(|arg| match arg {
                    syn::GenericArgument::Type(inner) => Some(inner),
                    _ => None,
                })
                .collect();
            let mutex_like = matches!(last.ident.to_string().as_str(), "Mutex" | "StdMutex");
            let mut visiting = Vec::new();
            let unit_arg = type_args
                .iter()
                .any(|inner| resolves_to_unit(inner, aliases, &mut visiting));
            if mutex_like && unit_arg {
                return true;
            }
            type_args
                .iter()
                .any(|inner| ty_contains_unit_mutex(inner, aliases))
        }
        syn::Type::Reference(r) => ty_contains_unit_mutex(&r.elem, aliases),
        syn::Type::Paren(p) => ty_contains_unit_mutex(&p.elem, aliases),
        syn::Type::Group(g) => ty_contains_unit_mutex(&g.elem, aliases),
        syn::Type::Tuple(t) => t
            .elems
            .iter()
            .any(|inner| ty_contains_unit_mutex(inner, aliases)),
        syn::Type::Array(a) => ty_contains_unit_mutex(&a.elem, aliases),
        syn::Type::Slice(s) => ty_contains_unit_mutex(&s.elem, aliases),
        syn::Type::Ptr(p) => ty_contains_unit_mutex(&p.elem, aliases),
        _ => false,
    }
}

/// True when the type is the unit type `()`, resolving `type` aliases on the
/// way (`type U = ();`). Cycle-safe via the visiting list.
fn resolves_to_unit(
    ty: &syn::Type,
    aliases: &HashMap<String, syn::Path>,
    visiting: &mut Vec<String>,
) -> bool {
    match ty {
        syn::Type::Tuple(tuple) => tuple.elems.is_empty(),
        syn::Type::Path(path) => {
            let Some(last) = path.path.segments.last() else {
                return false;
            };
            if !matches!(last.arguments, syn::PathArguments::None) {
                return false;
            }
            let name = last.ident.to_string();
            if visiting.contains(&name) {
                return false;
            }
            let Some(target) = aliases.get(&name) else {
                return false;
            };
            visiting.push(name);
            let resolved = syn::TypePath {
                qself: None,
                path: target.clone(),
            };
            let unit = resolves_to_unit(&syn::Type::Path(resolved), aliases, visiting);
            visiting.pop();
            unit
        }
        _ => false,
    }
}

/// Collect crate-wide `type` aliases so static types can resolve through
/// them. Aliases live at module top level (also inside inline mods).
fn collect_type_aliases(items: &[Item], aliases: &mut HashMap<String, syn::Path>) {
    for item in items {
        match item {
            Item::Type(ty) => {
                if let syn::Type::Path(path) = &*ty.ty {
                    aliases.insert(ty.ident.to_string(), path.path.clone());
                }
            }
            Item::Mod(module) => {
                if let Some((_, inner)) = &module.content {
                    collect_type_aliases(inner, aliases);
                }
            }
            _ => {}
        }
    }
}

/// One scanned fn (or impl/trait method) with its collected facts.
struct ScannedFn {
    file: String,
    /// Module path within the file ("" for file top level, "child" for a fn
    /// inside `mod child { ... }`), so `super::` calls from inline child mods
    /// resolve to the parent module's fns.
    module: String,
    name: String,
    /// Impl type when this fn is a method (`impl Wrapper { fn env_lock }`),
    /// so `Wrapper::env_lock` and method-call lock acquisition resolve.
    impl_type: Option<String>,
    /// True when this method comes from a trait impl (`impl T for X`):
    /// Rust resolves inherent impls before trait impls, so method calls
    /// only reach trait impls when no inherent method has that name.
    is_trait_impl: bool,
    env_writes: Vec<String>,
    lock_calls: Vec<(String, String)>,
    /// Ordered event stream for the R1 coverage check (see ScanEvent).
    events: Vec<ScanEvent>,
    unit_mutex_statics: Vec<String>,
}

/// Unit-mutex statics declared at module top level, outside any fn.
struct TopLevelStatic {
    file: String,
    name: String,
}

fn scan_fn(
    file: &str,
    module: &str,
    name: &str,
    func: &ItemFn,
    aliases: &HashMap<String, syn::Path>,
) -> ScannedFn {
    let mut scan = FnScan {
        aliases: aliases.clone(),
        ..FnScan::default()
    };
    scan.visit_item_fn(func);
    ScannedFn {
        file: file.to_string(),
        module: module.to_string(),
        name: name.to_string(),
        impl_type: None,
        is_trait_impl: false,
        env_writes: scan.env_writes,
        lock_calls: scan.lock_calls,
        events: scan.events,
        unit_mutex_statics: scan.unit_mutex_statics,
    }
}

fn walk_items(
    file: &str,
    items: &[Item],
    aliases: &HashMap<String, syn::Path>,
    fns: &mut Vec<ScannedFn>,
    statics: &mut Vec<TopLevelStatic>,
) {
    walk_module_items(file, "", items, aliases, fns, statics);
}

fn walk_module_items(
    file: &str,
    module: &str,
    items: &[Item],
    aliases: &HashMap<String, syn::Path>,
    fns: &mut Vec<ScannedFn>,
    statics: &mut Vec<TopLevelStatic>,
) {
    for item in items {
        match item {
            Item::Fn(func) => {
                let name = func.sig.ident.to_string();
                fns.push(scan_fn(file, module, &name, func, aliases));
            }
            Item::Impl(imp) => {
                let impl_type = type_name(&imp.self_ty).map(|name| name.to_string());
                let is_trait_impl = imp.trait_.is_some();
                for impl_item in &imp.items {
                    if let syn::ImplItem::Fn(method) = impl_item {
                        let name = method.sig.ident.to_string();
                        let mut scan = FnScan {
                            aliases: aliases.clone(),
                            impl_type: impl_type.clone(),
                            ..FnScan::default()
                        };
                        scan.visit_impl_item_fn(method);
                        fns.push(ScannedFn {
                            file: file.to_string(),
                            module: module.to_string(),
                            name,
                            impl_type: impl_type.clone(),
                            is_trait_impl,
                            env_writes: scan.env_writes,
                            lock_calls: scan.lock_calls,
                            events: scan.events,
                            unit_mutex_statics: scan.unit_mutex_statics,
                        });
                    }
                }
            }
            Item::Trait(trait_) => {
                for trait_item in &trait_.items {
                    if let syn::TraitItem::Fn(method) = trait_item {
                        if method.default.is_some() {
                            let name = method.sig.ident.to_string();
                            let mut scan = FnScan {
                                aliases: aliases.clone(),
                                ..FnScan::default()
                            };
                            scan.visit_trait_item_fn(method);
                            fns.push(ScannedFn {
                                file: file.to_string(),
                                module: module.to_string(),
                                name,
                                impl_type: None,
                                is_trait_impl: false,
                                env_writes: scan.env_writes,
                                lock_calls: scan.lock_calls,
                                events: scan.events,
                                unit_mutex_statics: scan.unit_mutex_statics,
                            });
                        }
                    }
                }
            }
            Item::Mod(module_item) => {
                if let Some((_, inner)) = &module_item.content {
                    let child = if module.is_empty() {
                        module_item.ident.to_string()
                    } else {
                        format!("{module}::{}", module_item.ident)
                    };
                    walk_module_items(file, &child, inner, aliases, fns, statics);
                }
            }
            Item::Static(stat) if ty_contains_unit_mutex(&stat.ty, aliases) => {
                statics.push(TopLevelStatic {
                    file: file.to_string(),
                    name: stat.ident.to_string(),
                });
            }
            _ => {}
        }
    }
}

fn collect_rs_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries =
        std::fs::read_dir(dir).unwrap_or_else(|err| panic!("read_dir {}: {err}", dir.display()));
    for entry in entries {
        let entry = entry.expect("read_dir entry");
        let path = entry.path();
        if path.is_dir() {
            collect_rs_files(&path, out);
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            out.push(path);
        }
    }
}

/// Path relative to the package root, matching ALLOWLIST keys ("src/x.rs").
fn rel_path(file: &Path) -> String {
    file.strip_prefix(env!("CARGO_MANIFEST_DIR"))
        .unwrap_or(file)
        .to_string_lossy()
        .replace('\\', "/")
}

/// Name of a plain self type (`impl Wrapper { .. }`), ignoring generics and
/// paths; None for anything else (`impl Trait for X`, generic params).
fn type_name(ty: &syn::Type) -> Option<String> {
    match ty {
        syn::Type::Path(path) => path.path.segments.last().map(|seg| seg.ident.to_string()),
        _ => None,
    }
}

/// True when the fn called as `qualifier::name` (`crate::tests::env_lock`
/// stores qualifier `crate::tests`) resolves to a genuine lock: a fn in the
/// scan that owns a unit-mutex static (canonical lock fn), or one that
/// calls another genuine lock (wrapper). Follows the chain transitively,
/// stopping on cycles (a cyclic chain locks nothing).
fn lock_call_is_genuine(
    fns: &[ScannedFn],
    imports: &HashMap<(String, String), (String, String)>,
    caller_file: &str,
    caller_module: &str,
    qualifier: &str,
    name: &str,
    visiting: &mut Vec<(String, String)>,
) -> bool {
    // Unprovable method syntax (unknown receiver, shadowed local, Self
    // outside any impl): never a genuine lock. No lock call is safe by
    // guesswork.
    if qualifier == "<method>" {
        return false;
    }
    let targets: Vec<(String, String)> = if qualifier.is_empty() {
        // Unqualified call: resolve via an explicit `use` import if one
        // exists, otherwise a fn defined in the caller's own module.
        match imports.get(&(caller_file.to_string(), name.to_string())) {
            Some((file, module)) => {
                if module.is_empty() {
                    vec![(file.to_string(), name.to_string())]
                } else {
                    vec![
                        (file.to_string(), format!("{module}::{name}")),
                        (file.to_string(), name.to_string()),
                    ]
                }
            }
            None => vec![(caller_file.to_string(), name.to_string())],
        }
    } else {
        let trimmed = qualifier.trim_end_matches("::");
        if trimmed == "super" {
            // super:: from an inline child mod: the parent module of the
            // caller's module path, same file. At file top level super:: is
            // crate-rooted, resolved by canonical_module below.
            let parent = parent_module(caller_module);
            return resolve_in_module(fns, imports, caller_file, &parent, name, visiting);
        }
        // Type-qualified lock call (`Wrapper::lock_env()`, `Self::lock_env()`
        // after the Self rewrite): resolve to methods of that type across
        // impls in the scan. Falls back to canonical_module for module
        // qualifiers (`crate::tests`, `crate::tui`).
        if let Some((file, module)) = canonical_module(caller_file, trimmed) {
            if module.is_empty() {
                vec![(file, name.to_string())]
            } else {
                vec![
                    (file.clone(), format!("{module}::{name}")),
                    (file, name.to_string()),
                ]
            }
        } else if fns
            .iter()
            .any(|func| func.impl_type.as_deref() == Some(trimmed))
        {
            // Impl methods of this type exist; resolve by name across impls.
            // Only that type's impls match, so a same-named fake method on
            // another type cannot shield it. The type rides in the target
            // key so cross-type chains do not trip the cycle guard.
            vec![(format!("<any>:{trimmed}"), name.to_string())]
        } else {
            return false;
        }
    };
    targets.into_iter().any(|target| {
        if visiting.contains(&target) {
            return false;
        }
        // `<any>:Type` target (Type::/method-call with a resolved receiver
        // type): candidates are impl methods of that exact type with the lock
        // name; free fns never satisfy a method call. Rust resolves inherent
        // impls before trait impls: when an inherent method with the name
        // exists, trait impls are shadowed and never run, so they cannot
        // vouch for the call.
        let candidates: Vec<&ScannedFn> = if let Some(ty) = target.0.strip_prefix("<any>:") {
            let has_inherent = fns.iter().any(|func| {
                func.impl_type.as_deref() == Some(ty)
                    && !func.is_trait_impl
                    && (func.name == target.1 || func.name == name)
            });
            fns.iter()
                .filter(|func| {
                    func.impl_type.as_deref() == Some(ty)
                        && (!func.is_trait_impl || !has_inherent)
                        && (func.name == target.1 || func.name == name)
                })
                .collect()
        } else {
            fns.iter()
                .filter(|func| {
                    func.file == target.0 && (func.name == target.1 || func.name == name)
                })
                .collect()
        };
        candidates.into_iter().any(|candidate| {
            if candidate.unit_mutex_statics.len() == 1 {
                return true;
            }
            visiting.push(target.clone());
            let genuine = candidate.lock_calls.iter().any(|(qual, lock)| {
                lock_call_is_genuine(
                    fns,
                    imports,
                    &candidate.file,
                    &candidate.module,
                    qual,
                    lock,
                    visiting,
                )
            });
            visiting.pop();
            genuine
        })
    })
}

/// Parent module path of a module path: "a::b" -> "a", "" -> "" (file top
/// level has no parent in-file; super:: there is crate-rooted).
fn parent_module(module: &str) -> String {
    match module.rsplit_once("::") {
        Some((parent, _)) => parent.to_string(),
        None => String::new(),
    }
}

/// Resolve a lock name in an explicit module of a file, mirroring the
/// candidate-search used for unqualified calls: qualified name first, plain
/// name fallback.
fn resolve_in_module(
    fns: &[ScannedFn],
    imports: &HashMap<(String, String), (String, String)>,
    file: &str,
    module: &str,
    name: &str,
    visiting: &mut Vec<(String, String)>,
) -> bool {
    let targets: Vec<(String, String)> = if module.is_empty() {
        vec![(file.to_string(), name.to_string())]
    } else {
        vec![
            (file.to_string(), format!("{module}::{name}")),
            (file.to_string(), name.to_string()),
        ]
    };
    targets.into_iter().any(|target| {
        if visiting.contains(&target) {
            return false;
        }
        let Some(candidate) = fns
            .iter()
            .find(|func| func.file == target.0 && (func.name == target.1 || func.name == name))
        else {
            return false;
        };
        if candidate.unit_mutex_statics.len() == 1 {
            return true;
        }
        visiting.push(target);
        let genuine = candidate.lock_calls.iter().any(|(qual, lock)| {
            lock_call_is_genuine(
                fns,
                imports,
                &candidate.file,
                &candidate.module,
                qual,
                lock,
                visiting,
            )
        });
        visiting.pop();
        genuine
    })
}

/// Map a lock-fn qualifier to its defining file and module path:
/// `crate::test_env_lock` lives in src/lib.rs (the test file itself for a
/// tests/ integration binary, which is its own crate root),
/// `crate::tests::env_lock` in src/tests.rs, `crate::tui::*` in src/tui.rs,
/// `crate::<mod>::*` in src/<mod>.rs. Returns None for unresolvable
/// qualifiers: no lock call is safe by guesswork.
fn canonical_module(caller_file: &str, qualifier: &str) -> Option<(String, String)> {
    if qualifier == "crate" {
        let file = if caller_file.starts_with("tests/") {
            caller_file.to_string()
        } else {
            "src/lib.rs".to_string()
        };
        return Some((file, String::new()));
    }
    let mut segments = qualifier.split("::").peekable();
    if segments.next() != Some("crate") {
        return None;
    }
    let module = segments.next()?;
    if segments.peek().is_some() {
        return None;
    }
    match module {
        "tests" => Some(("src/tests.rs".to_string(), "tests".to_string())),
        "tui" => Some(("src/tui.rs".to_string(), "tui".to_string())),
        other => Some((format!("src/{other}.rs"), other.to_string())),
    }
}

/// Local name -> defining location for lock-fn imports across files.
type LockImports = HashMap<(String, String), (String, String)>;

/// Scan every file's `use` items for explicit imports of lock fns
/// (`use crate::tests::lock_env;`), mapping (importing file, local name) to
/// (defining file, module path), and for renames of env writes
/// (`use std::env::set_var as sv;`), which are refused because a renamed
/// write is invisible to name-based detection. Only explicit imports make an
/// unqualified call resolvable to another file's fn; the guard never guesses.
fn collect_lock_imports(files: &[PathBuf]) -> (LockImports, Vec<String>) {
    let mut imports: LockImports = HashMap::new();
    let mut env_write_renames = Vec::new();
    for file in files {
        let Ok(source) = std::fs::read_to_string(file) else {
            continue;
        };
        let Ok(parsed) = syn::parse_file(&source) else {
            continue;
        };
        let rel = rel_path(file);
        walk_imports(&rel, &parsed.items, &mut imports, &mut env_write_renames);
    }
    (imports, env_write_renames)
}

fn walk_imports(
    file: &str,
    items: &[Item],
    imports: &mut HashMap<(String, String), (String, String)>,
    env_write_renames: &mut Vec<String>,
) {
    for item in items {
        match item {
            Item::Use(use_item) => {
                record_lock_import(file, &use_item.tree, "", imports, env_write_renames);
            }
            Item::Mod(module) => {
                if let Some((_, inner)) = &module.content {
                    walk_imports(file, inner, imports, env_write_renames);
                }
            }
            _ => {}
        }
    }
}

/// Record lock-fn imports from a `use` tree, accumulating the path prefix
/// through `use a::{b, c}` groups. A group item that is itself a plain name
/// resolves to prefix::name. Renames are refused: a renamed lock breaks the
/// call-site lock-name convention, and a renamed env write would be
/// invisible to name-based detection, so either is reported instead of
/// resolved through.
fn record_lock_import(
    file: &str,
    tree: &syn::UseTree,
    prefix: &str,
    imports: &mut HashMap<(String, String), (String, String)>,
    env_write_renames: &mut Vec<String>,
) {
    match tree {
        syn::UseTree::Path(path) => {
            let extended = if prefix.is_empty() {
                path.ident.to_string()
            } else {
                format!("{prefix}::{}", path.ident)
            };
            record_lock_import(file, &path.tree, &extended, imports, env_write_renames);
        }
        syn::UseTree::Name(name) => {
            let path = if prefix.is_empty() {
                name.ident.to_string()
            } else {
                format!("{prefix}::{}", name.ident)
            };
            record_lock_import_path(file, &path, imports);
        }
        syn::UseTree::Group(group) => {
            for item in &group.items {
                record_lock_import(file, item, prefix, imports, env_write_renames);
            }
        }
        syn::UseTree::Rename(rename) => {
            if ENV_WRITE_NAMES.contains(&rename.ident.to_string().as_str()) {
                env_write_renames.push(format!(
                    "  [R1] {file} renames env write `{}` as `{}`; call it by its plain name so the guard can see the write",
                    rename.ident, rename.rename
                ));
            }
        }
        syn::UseTree::Glob(_) => {}
    }
}

/// Register one concrete import path when its last segment is a LOCK_NAMES
/// name and its qualifier resolves to a canonical module.
fn record_lock_import_path(
    file: &str,
    path: &str,
    imports: &mut HashMap<(String, String), (String, String)>,
) {
    let segments: Vec<&str> = path.split("::").collect();
    if segments.len() < 2 {
        return;
    }
    let (qualifier, name) = segments.split_at(segments.len() - 1);
    let name = name[0];
    if LOCK_NAMES.contains(&name) {
        let qualifier = qualifier.join("::");
        if let Some((def_file, module)) = canonical_module(file, &qualifier) {
            imports.insert((file.to_string(), name.to_string()), (def_file, module));
        }
    }
}

#[test]
fn test_env_convention_is_enforced() {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mut files = Vec::new();
    for dir in ["src", "tests"] {
        let mut scoped = Vec::new();
        collect_rs_files(&manifest.join(dir), &mut scoped);
        assert!(
            !scoped.is_empty(),
            "no rust sources under {}",
            manifest.join(dir).display()
        );
        files.extend(scoped);
    }
    let build_rs = manifest.join("build.rs");
    if build_rs.is_file() {
        files.push(build_rs);
    }
    files.sort();

    let mut fns = Vec::new();
    let mut statics = Vec::new();
    // Crate-wide type aliases collected first (see ty_contains_unit_mutex):
    // every file's top-level `type X = ...;` entries, so `static L: M` with
    // `type M = Mutex<()>;` still counts as a unit-mutex static.
    let mut aliases: HashMap<String, syn::Path> = HashMap::new();
    for file in &files {
        let source = std::fs::read_to_string(file)
            .unwrap_or_else(|err| panic!("read {}: {err}", file.display()));
        let parsed: File = syn::parse_file(&source).unwrap_or_else(|err| {
            panic!(
                "{} does not parse; the guard is blind to it: {err}",
                file.display()
            )
        });
        collect_type_aliases(&parsed.items, &mut aliases);
    }
    for file in &files {
        let source = std::fs::read_to_string(file)
            .unwrap_or_else(|err| panic!("read {}: {err}", file.display()));
        let parsed: File = syn::parse_file(&source).unwrap_or_else(|err| {
            panic!(
                "{} does not parse; the guard is blind to it: {err}",
                file.display()
            )
        });
        let rel = rel_path(file);
        walk_items(&rel, &parsed.items, &aliases, &mut fns, &mut statics);
    }

    let mut violations = Vec::new();

    // R1: env writes need a genuine lock acquisition in the same fn body, or
    // an allowlist entry with written evidence. Genuine means the callee owns
    // a unit-mutex static (canonical lock fn) or calls another genuine lock
    // (wrapper); a fn merely named like a lock satisfies nothing.
    let (imports, env_write_renames) = collect_lock_imports(&files);
    violations.extend(env_write_renames);
    let mut allowlist_used = vec![false; ALLOWLIST.len()];
    for func in &fns {
        if func.env_writes.is_empty() {
            continue;
        }
        if let Some(slot) = ALLOWLIST
            .iter()
            .position(|(file, name, _)| *file == func.file && *name == func.name)
        {
            allowlist_used[slot] = true;
            continue;
        }
        // Order-sensitive coverage: walk the event stream. A write is only
        // covered by a lock acquired earlier in the same closure scope: a
        // lock guard held by the parent body does not cover writes made by
        // a spawned thread or a deferred closure (the guard may be dropped
        // by then), and a write before the lock call races with everything
        // between the fn start and the acquisition. Each closure depth
        // carries its own locked flag; a lock at one depth never covers a
        // write at another.
        let mut uncovered_write = false;
        let mut locked_by_depth: Vec<bool> = vec![false];
        for event in &func.events {
            match event {
                ScanEvent::EnterClosure => locked_by_depth.push(false),
                ScanEvent::ExitClosure => {
                    locked_by_depth.pop();
                }
                ScanEvent::Write => {
                    if !locked_by_depth.last().copied().unwrap_or(false) {
                        uncovered_write = true;
                        break;
                    }
                }
                ScanEvent::Lock(qual, lock) => {
                    let mut visiting = Vec::new();
                    let genuine = lock_call_is_genuine(
                        &fns,
                        &imports,
                        &func.file,
                        &func.module,
                        qual,
                        lock,
                        &mut visiting,
                    );
                    if genuine {
                        if let Some(flag) = locked_by_depth.last_mut() {
                            *flag = true;
                        }
                    }
                }
            }
        }
        if !uncovered_write {
            continue;
        }
        violations.push(format!(
            "  [R1] {} fn `{}` writes env ({}) without acquiring a genuine shared env lock",
            func.file,
            func.name,
            func.env_writes.join(", ")
        ));
        violations.push(
            "       fix: take the lock at fn start via your module's wrapper over crate::tests::env_lock / crate::test_env_lock (a fn merely named like a lock does not count), or, if the mutation is provably race-free, add an entry to ALLOWLIST in src/test_env_guard.rs with the evidence".to_string()
        );
    }

    // Stale allowlist entries: the evidence must keep matching reality.
    for (slot, (file, name, _)) in ALLOWLIST.iter().enumerate() {
        if !allowlist_used[slot] {
            violations.push(format!(
                "  [stale] ALLOWLIST entry ({file}, `{name}`) no longer matches an env-writing fn; remove it, or update it if the fn was renamed"
            ));
        }
    }

    // R3: private unit-mutex lock islands.
    let mut tests_lock_owners: HashMap<String, String> = HashMap::new();
    for func in &fns {
        if func.unit_mutex_statics.is_empty() {
            continue;
        }
        let exempted = CANONICAL_LOCK_FNS
            .iter()
            .any(|(file, name)| *file == func.file && *name == func.name)
            || is_tests_lock_fn(&func.file, &func.name);
        if exempted && func.unit_mutex_statics.len() > 1 {
            violations.push(format!(
                "  [R3] {} fn `{}` declares {} unit-mutex statics {}; an exempted lock fn must own exactly one: a second island inside it lets two env windows race without serializing. Remove the extra static(s)",
                func.file,
                func.name,
                func.unit_mutex_statics.len(),
                func.unit_mutex_statics.join(", ")
            ));
            continue;
        }
        if CANONICAL_LOCK_FNS
            .iter()
            .any(|(file, name)| *file == func.file && *name == func.name)
        {
            continue;
        }
        if is_tests_lock_fn(&func.file, &func.name) {
            let owner = tests_lock_owners
                .entry(func.file.clone())
                .or_insert_with(|| func.name.clone());
            if *owner == func.name {
                continue;
            }
            violations.push(format!(
                "  [R3] {} fn `{}` declares a second unit-mutex lock fn in a binary that already has `{owner}`; two islands in the same test binary can race each other. Merge them into one per-file lock fn",
                func.file, func.name
            ));
            continue;
        }
        violations.push(format!(
            "  [R3] {} fn `{}` declares private unit-mutex static(s) {}; module-private env locks let cross-module env windows race (the PR #240 bug class). Reuse crate::tests::env_lock / crate::test_env_lock",
            func.file,
            func.name,
            func.unit_mutex_statics.join(", ")
        ));
    }
    for stat in &statics {
        violations.push(format!(
            "  [R3] {} static `{}` is a private unit-mutex env lock outside the canonical lock fns; reuse crate::tests::env_lock / crate::test_env_lock",
            stat.file, stat.name
        ));
    }

    assert!(
        violations.is_empty(),
        "test env-lock convention violations:\n{}",
        violations.join("")
    );
}
